// frontend/src/pages/Announcements.tsx
import { useEffect, useState } from 'react';
import api from '../utils/api';
import type { Announcement } from '../types';
import { Megaphone, Plus, Edit, Trash2 } from 'lucide-react';
import { useAuth } from '../contexts/AuthContext';

export default function Announcements() {
  const { user } = useAuth();
  const [announcements, setAnnouncements] = useState<Announcement[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    api.get('/announcements').then(res => { setAnnouncements(res.data); setLoading(false); }).catch(() => setLoading(false));
  }, []);

  const deleteAnnouncement = async (id: string) => {
    if (!confirm('Delete this announcement?')) return;
    try {
      await api.delete(`/announcements/${id}`);
      setAnnouncements(announcements.filter(a => a.id !== id));
    } catch (error) { console.error('Error:', error); }
  };

  const getAudienceColor = (audience: string) => {
    switch (audience) {
      case 'ALL': return 'bg-indigo-100 text-indigo-700';
      case 'TEACHERS': return 'bg-green-100 text-green-700';
      case 'STUDENTS': return 'bg-blue-100 text-blue-700';
      case 'PARENTS': return 'bg-amber-100 text-amber-700';
      default: return 'bg-gray-100 text-gray-700';
    }
  };

  if (loading) return <div className="flex items-center justify-center h-64"><div className="animate-spin rounded-full h-8 w-8 border-b-2 border-indigo-600"></div></div>;

  return (
    <div>
      <div className="flex items-center justify-between mb-6">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">Announcements</h1>
          <p className="text-gray-500 mt-1">{announcements.length} announcements</p>
        </div>
        {user?.role === 'ADMIN' && (
          <button className="flex items-center gap-2 bg-indigo-600 text-white px-4 py-2 rounded-lg hover:bg-indigo-700 transition">
            <Plus size={18} /> New Announcement
          </button>
        )}
      </div>

      <div className="space-y-4">
        {announcements.length === 0 ? (
          <div className="bg-white rounded-xl shadow-sm border text-center py-12">
            <Megaphone size={48} className="mx-auto mb-4 text-gray-300" />
            <p className="text-gray-500">No announcements yet</p>
          </div>
        ) : (
          announcements.map(announcement => (
            <div key={announcement.id} className="bg-white rounded-xl shadow-sm border p-6">
              <div className="flex items-start justify-between">
                <div className="flex-1">
                  <div className="flex items-center gap-3 mb-2">
                    <h2 className="text-lg font-semibold text-gray-900">{announcement.title}</h2>
                    <span className={`text-xs px-2 py-1 rounded-full ${getAudienceColor(announcement.audience)}`}>{announcement.audience}</span>
                  </div>
                  <p className="text-gray-600">{announcement.content}</p>
                  <p className="text-xs text-gray-400 mt-3">{new Date(announcement.createdAt).toLocaleDateString()}</p>
                </div>
                {user?.role === 'ADMIN' && (
                  <div className="flex items-center gap-1 ml-4">
                    <button className="p-1 hover:bg-gray-100 rounded"><Edit size={16} className="text-blue-500" /></button>
                    <button onClick={() => deleteAnnouncement(announcement.id)} className="p-1 hover:bg-gray-100 rounded"><Trash2 size={16} className="text-red-500" /></button>
                  </div>
                )}
              </div>
            </div>
          ))
        )}
      </div>
    </div>
  );
}

// frontend/src/app/pages/announcements/announcements.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ApiService } from '../../services/api.service';
import { AuthService } from '../../services/auth.service';

@Component({
  selector: 'app-announcements',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
    <div class="p-6">
      <div class="flex justify-between items-center mb-6">
        <h1 class="text-2xl font-bold text-gray-800">Announcements</h1>
        @if (isAdmin) {
          <button (click)="showAdd = true" class="px-4 py-2 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700">New Announcement</button>
        }
      </div>
      @if (loading) {
        <div class="flex justify-center py-12"><div class="animate-spin rounded-full h-12 w-12 border-b-2 border-indigo-600"></div></div>
      } @else {
        <div class="space-y-4">
          @for (a of announcements; track a.id) {
            <div class="bg-white rounded-xl shadow p-6">
              <div class="flex justify-between items-start">
                <div>
                  <h3 class="text-lg font-semibold text-gray-800">{{a.title}}</h3>
                  <p class="text-gray-600 mt-2">{{a.content}}</p>
                  <div class="flex gap-2 mt-3">
                    <span class="px-2 py-1 bg-indigo-100 text-indigo-700 rounded text-xs">{{a.audience}}</span>
                    <span class="text-xs text-gray-400">{{a.createdAt | date:'medium'}}</span>
                  </div>
                </div>
                @if (isAdmin) {
                  <button (click)="deleteAnnouncement(a.id)" class="text-red-400 hover:text-red-600"><i class="pi pi-trash"></i></button>
                }
              </div>
            </div>
          }
          @if (announcements.length === 0) {
            <div class="text-center py-12 text-gray-500">No announcements</div>
          }
        </div>
      }

      @if (showAdd) {
        <div class="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
          <div class="bg-white rounded-xl p-6 w-full max-w-lg">
            <h2 class="text-xl font-bold mb-4">New Announcement</h2>
            <form (ngSubmit)="addAnnouncement()">
              <div class="space-y-4">
                <div><label class="block text-sm font-medium mb-1">Title</label><input [(ngModel)]="newAnnouncement.title" name="title" class="w-full px-3 py-2 border rounded-lg" required></div>
                <div><label class="block text-sm font-medium mb-1">Content</label><textarea [(ngModel)]="newAnnouncement.content" name="content" class="w-full px-3 py-2 border rounded-lg" rows="4" required></textarea></div>
                <div><label class="block text-sm font-medium mb-1">Audience</label>
                  <select [(ngModel)]="newAnnouncement.audience" name="audience" class="w-full px-3 py-2 border rounded-lg">
                    <option value="ALL">All</option>
                    <option value="TEACHERS">Teachers</option>
                    <option value="STUDENTS">Students</option>
                    <option value="PARENTS">Parents</option>
                  </select>
                </div>
              </div>
              <div class="flex justify-end gap-3 mt-6">
                <button type="button" (click)="showAdd = false" class="px-4 py-2 border rounded-lg">Cancel</button>
                <button type="submit" class="px-4 py-2 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700">Publish</button>
              </div>
            </form>
          </div>
        </div>
      }
    </div>
  `
})
export class AnnouncementsComponent implements OnInit {
  announcements: any[] = [];
  loading = true;
  showAdd = false;
  isAdmin = false;
  newAnnouncement: any = { audience: 'ALL' };

  constructor(private api: ApiService, private auth: AuthService) {
    this.isAdmin = auth.currentUser?.role === 'ADMIN';
  }

  ngOnInit() { this.api.getAnnouncements().subscribe({ next: (res) => { this.announcements = res; this.loading = false; }, error: () => this.loading = false }); }
  addAnnouncement() { this.api.createAnnouncement(this.newAnnouncement).subscribe({ next: () => { this.showAdd = false; this.newAnnouncement = { audience: 'ALL' }; this.ngOnInit(); } }); }
  deleteAnnouncement(id: number) { if (confirm('Delete?')) { this.api.deleteAnnouncement(id).subscribe({ next: () => this.ngOnInit() }); } }
}
