// frontend/src/components/Layout.tsx
import { Outlet, Link, useNavigate, useLocation } from 'react-router-dom';
import { useAuth } from '../contexts/AuthContext';
import { useState } from 'react';
import {
  LayoutDashboard, Users, GraduationCap, BookOpen, Calendar,
  ClipboardList, DollarSign, Library, Bell, Megaphone, BarChart3,
  LogOut, Menu, X, ChevronDown
} from 'lucide-react';

export default function Layout() {
  const { user, logout } = useAuth();
  const navigate = useNavigate();
  const location = useLocation();
  const [sidebarOpen, setSidebarOpen] = useState(true);
  const [userMenuOpen, setUserMenuOpen] = useState(false);

  const handleLogout = () => {
    logout();
    navigate('/login');
  };

  const menuItems = [
    { path: '/dashboard', label: 'Dashboard', icon: LayoutDashboard, roles: ['ADMIN', 'TEACHER', 'STUDENT', 'PARENT', 'ACCOUNTANT'] },
    { path: '/students', label: 'Students', icon: GraduationCap, roles: ['ADMIN', 'TEACHER'] },
    { path: '/teachers', label: 'Teachers', icon: Users, roles: ['ADMIN'] },
    { path: '/classes', label: 'Classes', icon: BookOpen, roles: ['ADMIN', 'TEACHER'] },
    { path: '/subjects', label: 'Subjects', icon: BookOpen, roles: ['ADMIN', 'TEACHER'] },
    { path: '/attendance', label: 'Attendance', icon: ClipboardList, roles: ['ADMIN', 'TEACHER'] },
    { path: '/grades', label: 'Grades', icon: BarChart3, roles: ['ADMIN', 'TEACHER'] },
    { path: '/timetable', label: 'Timetable', icon: Calendar, roles: ['ADMIN', 'TEACHER', 'STUDENT'] },
    { path: '/fees', label: 'Fees', icon: DollarSign, roles: ['ADMIN', 'ACCOUNTANT'] },
    { path: '/library', label: 'Library', icon: Library, roles: ['ADMIN'] },
    { path: '/announcements', label: 'Announcements', icon: Megaphone, roles: ['ADMIN', 'TEACHER', 'STUDENT', 'PARENT'] },
    { path: '/notifications', label: 'Notifications', icon: Bell, roles: ['ADMIN', 'TEACHER', 'STUDENT', 'PARENT', 'ACCOUNTANT'] },
    { path: '/reports', label: 'Reports', icon: BarChart3, roles: ['ADMIN', 'TEACHER', 'ACCOUNTANT'] },
  ];

  const filteredMenu = menuItems.filter(item => user && item.roles.includes(user.role));

  return (
    <div className="min-h-screen bg-gray-50 flex">
      {/* Sidebar */}
      <aside className={`${sidebarOpen ? 'w-64' : 'w-0 overflow-hidden'} bg-indigo-900 text-white transition-all duration-300 flex flex-col fixed h-full z-30`}>
        <div className="p-4 border-b border-indigo-800">
          <h1 className="text-xl font-bold text-amber-400">Golden Academy</h1>
          <p className="text-xs text-indigo-300 mt-1">School Management System</p>
        </div>
        <nav className="flex-1 overflow-y-auto p-2">
          {filteredMenu.map(item => {
            const Icon = item.icon;
            const isActive = location.pathname === item.path;
            return (
              <Link
                key={item.path}
                to={item.path}
                className={`flex items-center gap-3 px-4 py-2.5 rounded-lg mb-1 transition-colors ${
                  isActive ? 'bg-indigo-700 text-white' : 'text-indigo-200 hover:bg-indigo-800 hover:text-white'
                }`}
              >
                <Icon size={18} />
                <span className="text-sm">{item.label}</span>
              </Link>
            );
          })}
        </nav>
      </aside>

      {/* Main Content */}
      <div className={`flex-1 ${sidebarOpen ? 'ml-64' : 'ml-0'} transition-all duration-300`}>
        {/* Header */}
        <header className="bg-white shadow-sm border-b sticky top-0 z-20">
          <div className="flex items-center justify-between px-6 py-3">
            <button onClick={() => setSidebarOpen(!sidebarOpen)} className="p-2 rounded-lg hover:bg-gray-100">
              {sidebarOpen ? <X size={20} /> : <Menu size={20} />}
            </button>
            <div className="relative">
              <button
                onClick={() => setUserMenuOpen(!userMenuOpen)}
                className="flex items-center gap-2 px-3 py-2 rounded-lg hover:bg-gray-100"
              >
                <div className="w-8 h-8 rounded-full bg-indigo-600 flex items-center justify-center text-white text-sm font-medium">
                  {user?.firstName?.[0]}{user?.lastName?.[0]}
                </div>
                <div className="text-left hidden sm:block">
                  <p className="text-sm font-medium text-gray-700">{user?.firstName} {user?.lastName}</p>
                  <p className="text-xs text-gray-500">{user?.role}</p>
                </div>
                <ChevronDown size={16} className="text-gray-400" />
              </button>
              {userMenuOpen && (
                <div className="absolute right-0 mt-2 w-48 bg-white rounded-lg shadow-lg border py-1">
                  <button
                    onClick={handleLogout}
                    className="w-full flex items-center gap-2 px-4 py-2 text-sm text-red-600 hover:bg-red-50"
                  >
                    <LogOut size={16} />
                    Sign Out
                  </button>
                </div>
              )}
            </div>
          </div>
        </header>

        {/* Page Content */}
        <main className="p-6">
          <Outlet />
        </main>
      </div>
    </div>
  );
}

// frontend/src/app/features/layout/layout.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { AuthService } from '../../core/services/auth.service';

@Component({
  selector: 'app-layout',
  standalone: true,
  imports: [CommonModule, RouterModule],
  template: `
    <div class="flex h-screen bg-gray-100">
      <!-- Sidebar -->
      <aside class="sidebar w-64 bg-white shadow-lg flex flex-col">
        <div class="p-6 border-b border-gray-100">
          <h1 class="text-xl font-bold text-primary-700">
            <i class="pi pi-building mr-2"></i>Golden Academy
          </h1>
          <p class="text-xs text-gray-500 mt-1">School Management System</p>
        </div>

        <nav class="flex-1 p-4 space-y-1 overflow-y-auto">
          <a routerLink="/dashboard" routerLinkActive="active" class="sidebar-link">
            <i class="pi pi-th-large"></i>
            <span>Dashboard</span>
          </a>

          @if (authService.hasRole(['Admin', 'Teacher'])) {
            <a routerLink="/students" routerLinkActive="active" class="sidebar-link">
              <i class="pi pi-users"></i>
              <span>Students</span>
            </a>
          }

          @if (authService.hasRole(['Admin'])) {
            <a routerLink="/staff" routerLinkActive="active" class="sidebar-link">
              <i class="pi pi-id-card"></i>
              <span>Staff</span>
            </a>
          }

          @if (authService.hasRole(['Admin'])) {
            <a routerLink="/classes" routerLinkActive="active" class="sidebar-link">
              <i class="pi pi-table"></i>
              <span>Classes</span>
            </a>
            <a routerLink="/subjects" routerLinkActive="active" class="sidebar-link">
              <i class="pi pi-book"></i>
              <span>Subjects</span>
            </a>
          }

          @if (authService.hasRole(['Admin', 'Teacher'])) {
            <a routerLink="/attendance" routerLinkActive="active" class="sidebar-link">
              <i class="pi pi-calendar-plus"></i>
              <span>Attendance</span>
            </a>
          }

          <a routerLink="/exams" routerLinkActive="active" class="sidebar-link">
            <i class="pi pi-file-edit"></i>
            <span>Exams</span>
          </a>

          <a routerLink="/grades" routerLinkActive="active" class="sidebar-link">
            <i class="pi pi-chart-bar"></i>
            <span>Grades</span>
          </a>

          @if (authService.hasRole(['Admin', 'Accountant'])) {
            <a routerLink="/fees" routerLinkActive="active" class="sidebar-link">
              <i class="pi pi-wallet"></i>
              <span>Fees</span>
            </a>
          }

          <a routerLink="/timetable" routerLinkActive="active" class="sidebar-link">
            <i class="pi pi-clock"></i>
            <span>Timetable</span>
          </a>

          <a routerLink="/library" routerLinkActive="active" class="sidebar-link">
            <i class="pi pi-bookmark"></i>
            <span>Library</span>
          </a>

          @if (authService.hasRole(['Admin'])) {
            <a routerLink="/notifications" routerLinkActive="active" class="sidebar-link">
              <i class="pi pi-bell"></i>
              <span>Notifications</span>
            </a>
          }
        </nav>

        <div class="p-4 border-t border-gray-100">
          <div class="flex items-center gap-3 mb-3">
            <div class="w-9 h-9 rounded-full bg-primary-100 flex items-center justify-center">
              <i class="pi pi-user text-primary-700"></i>
            </div>
            <div>
              <p class="text-sm font-medium text-gray-700">{{ authService.currentUser?.username }}</p>
              <p class="text-xs text-gray-500">{{ authService.currentUser?.role }}</p>
            </div>
          </div>
          <button (click)="authService.logout()" class="w-full text-left sidebar-link text-red-500 hover:bg-red-50 hover:text-red-700">
            <i class="pi pi-sign-out"></i>
            <span>Logout</span>
          </button>
        </div>
      </aside>

      <!-- Main content -->
      <main class="flex-1 overflow-y-auto">
        <header class="bg-white shadow-sm px-8 py-4 flex items-center justify-between">
          <div>
            <h2 class="text-lg font-semibold text-gray-800">Welcome back, {{ authService.currentUser?.username }}!</h2>
            <p class="text-sm text-gray-500">{{ today | date:'fullDate' }}</p>
          </div>
          <div class="flex items-center gap-4">
            <button class="relative p-2 text-gray-500 hover:text-gray-700">
              <i class="pi pi-bell text-lg"></i>
            </button>
          </div>
        </header>

        <div class="p-8">
          <router-outlet></router-outlet>
        </div>
      </main>
    </div>
  `
})
export class LayoutComponent {
  today = new Date();

  constructor(public authService: AuthService) {}
}
