// frontend/src/app/components/layout/layout.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule, Router } from '@angular/router';
import { AuthService } from '../../services/auth.service';

@Component({
  selector: 'app-layout',
  standalone: true,
  imports: [CommonModule, RouterModule],
  template: `
    <div class="flex h-screen bg-gray-100">
      <!-- Sidebar -->
      <aside class="w-64 bg-indigo-800 text-white flex flex-col">
        <div class="p-4 border-b border-indigo-700">
          <h1 class="text-xl font-bold">Golden Academy</h1>
          <p class="text-indigo-300 text-sm">School Management System</p>
        </div>
        <nav class="flex-1 p-4 space-y-1 overflow-y-auto">
          @for (item of menuItems; track item.path) {
            <a [routerLink]="item.path" routerLinkActive="bg-indigo-900 text-white"
               class="flex items-center px-3 py-2 rounded-lg text-indigo-200 hover:bg-indigo-700 hover:text-white transition">
              <i [class]="item.icon + ' mr-3 text-lg'"></i>
              <span>{{item.label}}</span>
            </a>
          }
        </nav>
        <div class="p-4 border-t border-indigo-700">
          <div class="flex items-center mb-3">
            <div class="w-8 h-8 bg-indigo-600 rounded-full flex items-center justify-center text-sm font-bold">
              {{user?.firstName?.charAt(0)}}{{user?.lastName?.charAt(0)}}
            </div>
            <div class="ml-3">
              <p class="text-sm font-medium">{{user?.firstName}} {{user?.lastName}}</p>
              <p class="text-xs text-indigo-300">{{user?.role}}</p>
            </div>
          </div>
          <button (click)="logout()" class="w-full px-3 py-2 text-sm bg-indigo-700 rounded hover:bg-indigo-600 transition">
            Sign Out
          </button>
        </div>
      </aside>
      <!-- Main Content -->
      <main class="flex-1 overflow-y-auto">
        <router-outlet></router-outlet>
      </main>
    </div>
  `
})
export class LayoutComponent {
  user: any;
  menuItems: { path: string; label: string; icon: string }[] = [];

  constructor(private auth: AuthService, private router: Router) {
    this.user = this.auth.currentUser;
    this.buildMenu();
  }

  private buildMenu() {
    const role = this.user?.role || '';
    const all = [
      { path: '/dashboard', label: 'Dashboard', icon: 'pi pi-home', roles: ['ADMIN', 'TEACHER', 'STUDENT', 'PARENT', 'ACCOUNTANT'] },
      { path: '/students', label: 'Students', icon: 'pi pi-users', roles: ['ADMIN', 'TEACHER'] },
      { path: '/teachers', label: 'Teachers', icon: 'pi pi-id-card', roles: ['ADMIN'] },
      { path: '/classes', label: 'Classes', icon: 'pi pi-building', roles: ['ADMIN', 'TEACHER'] },
      { path: '/subjects', label: 'Subjects', icon: 'pi pi-book', roles: ['ADMIN', 'TEACHER'] },
      { path: '/attendance', label: 'Attendance', icon: 'pi pi-check-square', roles: ['ADMIN', 'TEACHER'] },
      { path: '/grades', label: 'Grades', icon: 'pi pi-chart-bar', roles: ['ADMIN', 'TEACHER', 'STUDENT', 'PARENT'] },
      { path: '/timetable', label: 'Timetable', icon: 'pi pi-calendar', roles: ['ADMIN', 'TEACHER', 'STUDENT'] },
      { path: '/fees', label: 'Fees', icon: 'pi pi-wallet', roles: ['ADMIN', 'ACCOUNTANT'] },
      { path: '/library', label: 'Library', icon: 'pi pi-bookmark', roles: ['ADMIN', 'STUDENT'] },
      { path: '/notifications', label: 'Notifications', icon: 'pi pi-bell', roles: ['ADMIN', 'TEACHER', 'STUDENT', 'PARENT', 'ACCOUNTANT'] },
      { path: '/announcements', label: 'Announcements', icon: 'pi pi-megaphone', roles: ['ADMIN', 'TEACHER', 'STUDENT', 'PARENT', 'ACCOUNTANT'] },
      { path: '/reports', label: 'Reports', icon: 'pi pi-chart-line', roles: ['ADMIN', 'TEACHER', 'ACCOUNTANT'] },
    ];
    this.menuItems = all.filter(item => item.roles.includes(role));
  }

  logout() {
    this.auth.logout();
    this.router.navigate(['/login']);
  }
}

// frontend/src/components/Layout.tsx
import { Outlet, Link, useNavigate, useLocation } from 'react-router-dom';
import { useAuth } from '../contexts/AuthContext';
import { useState } from 'react';
import {
  LayoutDashboard, Users, GraduationCap, BookOpen, Calendar,
  ClipboardList, DollarSign, Library, Bell, Megaphone, BarChart3,
  LogOut, Menu, X, ChevronDown
} from 'lucide-react';

export default function Layout() {
  const { user, logout } = useAuth();
  const navigate = useNavigate();
  const location = useLocation();
  const [sidebarOpen, setSidebarOpen] = useState(true);
  const [userMenuOpen, setUserMenuOpen] = useState(false);

  const handleLogout = () => {
    logout();
    navigate('/login');
  };

  const menuItems = [
    { path: '/dashboard', label: 'Dashboard', icon: LayoutDashboard, roles: ['ADMIN', 'TEACHER', 'STUDENT', 'PARENT', 'ACCOUNTANT'] },
    { path: '/students', label: 'Students', icon: GraduationCap, roles: ['ADMIN', 'TEACHER'] },
    { path: '/teachers', label: 'Teachers', icon: Users, roles: ['ADMIN'] },
    { path: '/classes', label: 'Classes', icon: BookOpen, roles: ['ADMIN', 'TEACHER'] },
    { path: '/subjects', label: 'Subjects', icon: BookOpen, roles: ['ADMIN', 'TEACHER'] },
    { path: '/attendance', label: 'Attendance', icon: ClipboardList, roles: ['ADMIN', 'TEACHER'] },
    { path: '/grades', label: 'Grades', icon: BarChart3, roles: ['ADMIN', 'TEACHER'] },
    { path: '/timetable', label: 'Timetable', icon: Calendar, roles: ['ADMIN', 'TEACHER', 'STUDENT'] },
    { path: '/fees', label: 'Fees', icon: DollarSign, roles: ['ADMIN', 'ACCOUNTANT'] },
    { path: '/library', label: 'Library', icon: Library, roles: ['ADMIN'] },
    { path: '/announcements', label: 'Announcements', icon: Megaphone, roles: ['ADMIN', 'TEACHER', 'STUDENT', 'PARENT'] },
    { path: '/notifications', label: 'Notifications', icon: Bell, roles: ['ADMIN', 'TEACHER', 'STUDENT', 'PARENT', 'ACCOUNTANT'] },
    { path: '/reports', label: 'Reports', icon: BarChart3, roles: ['ADMIN', 'TEACHER', 'ACCOUNTANT'] },
  ];

  const filteredMenu = menuItems.filter(item => user && item.roles.includes(user.role));

  return (
    <div className="min-h-screen bg-gray-50 flex">
      {/* Sidebar */}
      <aside className={`${sidebarOpen ? 'w-64' : 'w-0 overflow-hidden'} bg-indigo-900 text-white transition-all duration-300 flex flex-col fixed h-full z-30`}>
        <div className="p-4 border-b border-indigo-800">
          <h1 className="text-xl font-bold text-amber-400">Golden Academy</h1>
          <p className="text-xs text-indigo-300 mt-1">School Management System</p>
        </div>
        <nav className="flex-1 overflow-y-auto p-2">
          {filteredMenu.map(item => {
            const Icon = item.icon;
            const isActive = location.pathname === item.path;
            return (
              <Link
                key={item.path}
                to={item.path}
                className={`flex items-center gap-3 px-4 py-2.5 rounded-lg mb-1 transition-colors ${
                  isActive ? 'bg-indigo-700 text-white' : 'text-indigo-200 hover:bg-indigo-800 hover:text-white'
                }`}
              >
                <Icon size={18} />
                <span className="text-sm">{item.label}</span>
              </Link>
            );
          })}
        </nav>
      </aside>

      {/* Main Content */}
      <div className={`flex-1 ${sidebarOpen ? 'ml-64' : 'ml-0'} transition-all duration-300`}>
        {/* Header */}
        <header className="bg-white shadow-sm border-b sticky top-0 z-20">
          <div className="flex items-center justify-between px-6 py-3">
            <button onClick={() => setSidebarOpen(!sidebarOpen)} className="p-2 rounded-lg hover:bg-gray-100">
              {sidebarOpen ? <X size={20} /> : <Menu size={20} />}
            </button>
            <div className="relative">
              <button
                onClick={() => setUserMenuOpen(!userMenuOpen)}
                className="flex items-center gap-2 px-3 py-2 rounded-lg hover:bg-gray-100"
              >
                <div className="w-8 h-8 rounded-full bg-indigo-600 flex items-center justify-center text-white text-sm font-medium">
                  {user?.firstName?.[0]}{user?.lastName?.[0]}
                </div>
                <div className="text-left hidden sm:block">
                  <p className="text-sm font-medium text-gray-700">{user?.firstName} {user?.lastName}</p>
                  <p className="text-xs text-gray-500">{user?.role}</p>
                </div>
                <ChevronDown size={16} className="text-gray-400" />
              </button>
              {userMenuOpen && (
                <div className="absolute right-0 mt-2 w-48 bg-white rounded-lg shadow-lg border py-1">
                  <button
                    onClick={handleLogout}
                    className="w-full flex items-center gap-2 px-4 py-2 text-sm text-red-600 hover:bg-red-50"
                  >
                    <LogOut size={16} />
                    Sign Out
                  </button>
                </div>
              )}
            </div>
          </div>
        </header>

        {/* Page Content */}
        <main className="p-6">
          <Outlet />
        </main>
      </div>
    </div>
  );
}
