// frontend/src/pages/Timetable.tsx
import { useEffect, useState } from 'react';
import api from '../utils/api';
import type { TimetableSlot, ClassData } from '../types';
import { Clock } from 'lucide-react';

const DAYS = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'];
const COLORS = ['bg-blue-100 text-blue-800', 'bg-green-100 text-green-800', 'bg-purple-100 text-purple-800', 'bg-amber-100 text-amber-800', 'bg-rose-100 text-rose-800', 'bg-cyan-100 text-cyan-800'];

export default function Timetable() {
  const [classes, setClasses] = useState<ClassData[]>([]);
  const [selectedClass, setSelectedClass] = useState('');
  const [slots, setSlots] = useState<TimetableSlot[]>([]);
  const [loading, setLoading] = useState(false);

  useEffect(() => { api.get('/classes').then(res => setClasses(res.data)); }, []);

  useEffect(() => {
    if (selectedClass) {
      setLoading(true);
      api.get(`/timetable/class/${selectedClass}`).then(res => { setSlots(res.data); setLoading(false); }).catch(() => setLoading(false));
    }
  }, [selectedClass]);

  const getSlotsByDay = (day: string) => slots.filter(s => s.day === day).sort((a, b) => a.startTime.localeCompare(b.startTime));
  const getSubjectColor = (subjectId: string) => {
    const subjects = [...new Set(slots.map(s => s.subjectId))];
    return COLORS[subjects.indexOf(subjectId) % COLORS.length];
  };

  return (
    <div>
      <div className="mb-6">
        <h1 className="text-2xl font-bold text-gray-900">Timetable</h1>
        <p className="text-gray-500 mt-1">Class schedules and timetables</p>
      </div>

      <div className="bg-white rounded-xl shadow-sm border p-6 mb-6">
        <label className="block text-sm font-medium text-gray-700 mb-1">Select Class</label>
        <select value={selectedClass} onChange={(e) => setSelectedClass(e.target.value)}
          className="px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-indigo-500 outline-none">
          <option value="">Select Class</option>
          {classes.map(c => <option key={c.id} value={c.id}>{c.name} {c.section || ''}</option>)}
        </select>
      </div>

      {loading && <div className="flex items-center justify-center h-32"><div className="animate-spin rounded-full h-8 w-8 border-b-2 border-indigo-600"></div></div>}

      {selectedClass && !loading && (
        <div className="bg-white rounded-xl shadow-sm border overflow-x-auto">
          {slots.length === 0 ? (
            <div className="text-center py-12 text-gray-500">
              <Clock size={48} className="mx-auto mb-4 text-gray-300" />
              <p>No timetable entries for this class yet.</p>
            </div>
          ) : (
            <div className="min-w-[800px]">
              <div className="grid grid-cols-5 gap-px bg-gray-200">
                {DAYS.map(day => (
                  <div key={day} className="bg-indigo-50 px-4 py-3 text-center font-semibold text-indigo-900">{day}</div>
                ))}
              </div>
              <div className="grid grid-cols-5 gap-px bg-gray-200 min-h-[400px]">
                {DAYS.map(day => (
                  <div key={day} className="bg-white p-2 space-y-2">
                    {getSlotsByDay(day).map(slot => (
                      <div key={slot.id} className={`rounded-lg p-3 ${getSubjectColor(slot.subjectId)}`}>
                        <p className="font-medium text-sm">{slot.subject?.name}</p>
                        <p className="text-xs mt-1">{slot.startTime} - {slot.endTime}</p>
                        {slot.teacher && <p className="text-xs mt-1">{slot.teacher.user?.firstName} {slot.teacher.user?.lastName}</p>}
                        {slot.room && <p className="text-xs">Room: {slot.room}</p>}
                      </div>
                    ))}
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>
      )}
    </div>
  );
}

// frontend/src/app/features/timetable/timetable.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ApiService } from '../../core/services/api.service';
import { Timetable, SchoolClass, Subject } from '../../core/models/models';

@Component({
  selector: 'app-timetable',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
    <div>
      <div class="flex items-center justify-between mb-6">
        <h1 class="text-2xl font-bold text-gray-800">Timetable</h1>
        <button (click)="showForm = !showForm" class="bg-primary-600 text-white px-4 py-2 rounded-lg hover:bg-primary-700">
          <i class="pi pi-plus mr-2"></i>{{ showForm ? 'Cancel' : 'Add Entry' }}
        </button>
      </div>

      <div class="bg-white rounded-xl shadow-sm border border-gray-100 p-4 mb-6">
        <select [(ngModel)]="filterClassId" (ngModelChange)="load()" class="px-4 py-2 border border-gray-300 rounded-lg">
          <option [ngValue]="undefined">All Classes</option>
          @for (c of classes; track c.id) { <option [ngValue]="c.id">{{ c.name }} {{ c.section }}</option> }
        </select>
      </div>

      @if (showForm) {
        <div class="bg-white rounded-xl shadow-sm border border-gray-100 p-6 mb-6">
          <form (ngSubmit)="save()">
            <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
              <div>
                <label class="block text-sm font-medium text-gray-700 mb-1">Class</label>
                <select [(ngModel)]="form.classId" name="classId" class="w-full px-3 py-2 border border-gray-300 rounded-lg" required>
                  @for (c of classes; track c.id) { <option [ngValue]="c.id">{{ c.name }} {{ c.section }}</option> }
                </select>
              </div>
              <div>
                <label class="block text-sm font-medium text-gray-700 mb-1">Subject</label>
                <select [(ngModel)]="form.subjectId" name="subjectId" class="w-full px-3 py-2 border border-gray-300 rounded-lg" required>
                  @for (s of subjects; track s.id) { <option [ngValue]="s.id">{{ s.name }}</option> }
                </select>
              </div>
              <div>
                <label class="block text-sm font-medium text-gray-700 mb-1">Day</label>
                <select [(ngModel)]="form.dayOfWeek" name="dayOfWeek" class="w-full px-3 py-2 border border-gray-300 rounded-lg" required>
                  @for (d of days; track d) { <option [value]="d">{{ d }}</option> }
                </select>
              </div>
              <div>
                <label class="block text-sm font-medium text-gray-700 mb-1">Start Time</label>
                <input type="time" [(ngModel)]="form.startTime" name="startTime" class="w-full px-3 py-2 border border-gray-300 rounded-lg" required>
              </div>
              <div>
                <label class="block text-sm font-medium text-gray-700 mb-1">End Time</label>
                <input type="time" [(ngModel)]="form.endTime" name="endTime" class="w-full px-3 py-2 border border-gray-300 rounded-lg" required>
              </div>
            </div>
            <div class="mt-4">
              <button type="submit" class="bg-primary-600 text-white px-6 py-2 rounded-lg hover:bg-primary-700">Save</button>
            </div>
          </form>
        </div>
      }

      <!-- Timetable Grid by Day -->
      @for (day of days; track day) {
        @if (getEntriesForDay(day).length > 0) {
          <div class="mb-6">
            <h3 class="text-lg font-semibold text-gray-700 mb-3">{{ day }}</h3>
            <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
              @for (t of getEntriesForDay(day); track t.id) {
                <div class="bg-white rounded-xl shadow-sm border border-gray-100 p-4">
                  <div class="flex items-center justify-between mb-2">
                    <span class="text-sm font-medium text-primary-700">{{ t.subjectName }}</span>
                    <button (click)="deleteEntry(t.id)" class="text-red-400 hover:text-red-600"><i class="pi pi-times text-xs"></i></button>
                  </div>
                  <p class="text-xs text-gray-500">{{ t.className }}</p>
                  <p class="text-sm text-gray-700 mt-1"><i class="pi pi-clock mr-1"></i>{{ t.startTime }} - {{ t.endTime }}</p>
                </div>
              }
            </div>
          </div>
        }
      }

      @if (timetable.length === 0) {
        <div class="text-center py-12 text-gray-500">No timetable entries found</div>
      }
    </div>
  `
})
export class TimetableComponent implements OnInit {
  timetable: Timetable[] = [];
  classes: SchoolClass[] = [];
  subjects: Subject[] = [];
  filterClassId?: number;
  showForm = false;
  form: any = { dayOfWeek: 'Monday' };
  days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];

  constructor(private apiService: ApiService) {}

  ngOnInit(): void {
    this.load();
    this.apiService.getClasses().subscribe(c => this.classes = c);
    this.apiService.getSubjects().subscribe(s => this.subjects = s);
  }

  load(): void { this.apiService.getTimetable(this.filterClassId).subscribe(t => this.timetable = t); }

  getEntriesForDay(day: string): Timetable[] {
    return this.timetable.filter(t => t.dayOfWeek === day);
  }

  save(): void {
    this.apiService.createTimetable(this.form).subscribe(() => {
      this.load();
      this.showForm = false;
      this.form = { dayOfWeek: 'Monday' };
    });
  }

  deleteEntry(id: number): void {
    if (confirm('Are you sure?')) this.apiService.deleteTimetable(id).subscribe(() => this.load());
  }
}
