// frontend/src/pages/Teachers.tsx
import { useEffect, useState } from 'react';
import api from '../utils/api';
import type { Teacher } from '../types';
import { Search, Plus, Eye, Edit, Trash2, X } from 'lucide-react';

export default function Teachers() {
  const [teachers, setTeachers] = useState<Teacher[]>([]);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState('');
  const [selectedTeacher, setSelectedTeacher] = useState<Teacher | null>(null);
  const [showModal, setShowModal] = useState(false);

  useEffect(() => {
    fetchTeachers();
  }, []);

  const fetchTeachers = async () => {
    try {
      const { data } = await api.get('/teachers');
      setTeachers(data);
    } catch (error) {
      console.error('Error fetching teachers:', error);
    } finally {
      setLoading(false);
    }
  };

  const deleteTeacher = async (id: string) => {
    if (!confirm('Are you sure you want to delete this teacher?')) return;
    try {
      await api.delete(`/teachers/${id}`);
      setTeachers(teachers.filter(t => t.id !== id));
    } catch (error) {
      console.error('Error deleting teacher:', error);
    }
  };

  const viewTeacher = async (id: string) => {
    try {
      const { data } = await api.get(`/teachers/${id}`);
      setSelectedTeacher(data);
      setShowModal(true);
    } catch (error) {
      console.error('Error:', error);
    }
  };

  const filtered = teachers.filter(t =>
    `${t.user.firstName} ${t.user.lastName} ${t.employeeId}`.toLowerCase().includes(search.toLowerCase())
  );

  if (loading) return <div className="flex items-center justify-center h-64"><div className="animate-spin rounded-full h-8 w-8 border-b-2 border-indigo-600"></div></div>;

  return (
    <div>
      <div className="flex items-center justify-between mb-6">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">Teachers</h1>
          <p className="text-gray-500 mt-1">{teachers.length} total teachers</p>
        </div>
        <button className="flex items-center gap-2 bg-indigo-600 text-white px-4 py-2 rounded-lg hover:bg-indigo-700 transition">
          <Plus size={18} /> Add Teacher
        </button>
      </div>

      <div className="bg-white rounded-xl shadow-sm border">
        <div className="p-4 border-b">
          <div className="relative">
            <Search size={18} className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" />
            <input type="text" placeholder="Search teachers..." value={search} onChange={(e) => setSearch(e.target.value)}
              className="w-full pl-10 pr-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 outline-none" />
          </div>
        </div>
        <div className="overflow-x-auto">
          <table className="w-full">
            <thead className="bg-gray-50">
              <tr>
                <th className="text-left px-6 py-3 text-xs font-medium text-gray-500 uppercase">Teacher</th>
                <th className="text-left px-6 py-3 text-xs font-medium text-gray-500 uppercase">Employee ID</th>
                <th className="text-left px-6 py-3 text-xs font-medium text-gray-500 uppercase">Qualification</th>
                <th className="text-left px-6 py-3 text-xs font-medium text-gray-500 uppercase">Subjects</th>
                <th className="text-left px-6 py-3 text-xs font-medium text-gray-500 uppercase">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y">
              {filtered.map(teacher => (
                <tr key={teacher.id} className="hover:bg-gray-50">
                  <td className="px-6 py-4">
                    <div className="flex items-center gap-3">
                      <div className="w-8 h-8 rounded-full bg-green-100 flex items-center justify-center text-sm font-medium text-green-600">
                        {teacher.user.firstName[0]}{teacher.user.lastName[0]}
                      </div>
                      <div>
                        <p className="font-medium text-gray-900">{teacher.user.firstName} {teacher.user.lastName}</p>
                        <p className="text-sm text-gray-500">{teacher.user.email}</p>
                      </div>
                    </div>
                  </td>
                  <td className="px-6 py-4 text-sm text-gray-600">{teacher.employeeId}</td>
                  <td className="px-6 py-4 text-sm text-gray-600">{teacher.qualification || '-'}</td>
                  <td className="px-6 py-4">
                    <div className="flex flex-wrap gap-1">
                      {teacher.subjects?.map(s => (
                        <span key={s.subject.id} className="inline-flex px-2 py-0.5 text-xs bg-indigo-100 text-indigo-700 rounded-full">{s.subject.name}</span>
                      ))}
                    </div>
                  </td>
                  <td className="px-6 py-4">
                    <div className="flex items-center gap-2">
                      <button onClick={() => viewTeacher(teacher.id)} className="p-1 hover:bg-gray-100 rounded"><Eye size={16} className="text-gray-500" /></button>
                      <button className="p-1 hover:bg-gray-100 rounded"><Edit size={16} className="text-blue-500" /></button>
                      <button onClick={() => deleteTeacher(teacher.id)} className="p-1 hover:bg-gray-100 rounded"><Trash2 size={16} className="text-red-500" /></button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {showModal && selectedTeacher && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
          <div className="bg-white rounded-xl max-w-2xl w-full max-h-[90vh] overflow-y-auto">
            <div className="flex items-center justify-between p-6 border-b">
              <h2 className="text-lg font-semibold">Teacher Details</h2>
              <button onClick={() => setShowModal(false)} className="p-1 hover:bg-gray-100 rounded"><X size={20} /></button>
            </div>
            <div className="p-6 space-y-4">
              <div className="grid grid-cols-2 gap-4">
                <div><p className="text-sm text-gray-500">Name</p><p className="font-medium">{selectedTeacher.user.firstName} {selectedTeacher.user.lastName}</p></div>
                <div><p className="text-sm text-gray-500">Employee ID</p><p className="font-medium">{selectedTeacher.employeeId}</p></div>
                <div><p className="text-sm text-gray-500">Email</p><p className="font-medium">{selectedTeacher.user.email}</p></div>
                <div><p className="text-sm text-gray-500">Qualification</p><p className="font-medium">{selectedTeacher.qualification || '-'}</p></div>
                <div><p className="text-sm text-gray-500">Gender</p><p className="font-medium">{selectedTeacher.gender}</p></div>
                <div><p className="text-sm text-gray-500">Join Date</p><p className="font-medium">{new Date(selectedTeacher.joinDate).toLocaleDateString()}</p></div>
              </div>
              {selectedTeacher.classes && selectedTeacher.classes.length > 0 && (
                <div>
                  <h3 className="font-semibold mb-2">Classes</h3>
                  <div className="flex flex-wrap gap-2">
                    {selectedTeacher.classes.map(c => (
                      <span key={c.id} className="px-3 py-1 bg-purple-100 text-purple-700 rounded-full text-sm">{c.name} {c.section || ''}</span>
                    ))}
                  </div>
                </div>
              )}
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

// frontend/src/app/pages/teachers/teachers.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ApiService } from '../../services/api.service';

@Component({
  selector: 'app-teachers',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
    <div class="p-6">
      <div class="flex justify-between items-center mb-6">
        <h1 class="text-2xl font-bold text-gray-800">Teachers</h1>
        <div class="flex gap-3">
          <input type="text" [(ngModel)]="search" placeholder="Search teachers..." class="px-4 py-2 border rounded-lg focus:ring-2 focus:ring-indigo-500">
          <button (click)="showAdd = true" class="px-4 py-2 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700">Add Teacher</button>
        </div>
      </div>
      @if (loading) {
        <div class="flex justify-center py-12"><div class="animate-spin rounded-full h-12 w-12 border-b-2 border-indigo-600"></div></div>
      } @else {
        <div class="bg-white rounded-xl shadow overflow-hidden">
          <table class="w-full text-sm">
            <thead class="bg-gray-50">
              <tr>
                <th class="text-left px-6 py-3 font-medium text-gray-500">Name</th>
                <th class="text-left px-6 py-3 font-medium text-gray-500">Employee ID</th>
                <th class="text-left px-6 py-3 font-medium text-gray-500">Qualification</th>
                <th class="text-left px-6 py-3 font-medium text-gray-500">Subjects</th>
                <th class="text-left px-6 py-3 font-medium text-gray-500">Classes</th>
                <th class="text-left px-6 py-3 font-medium text-gray-500">Actions</th>
              </tr>
            </thead>
            <tbody>
              @for (teacher of filteredTeachers; track teacher.id) {
                <tr class="border-t hover:bg-gray-50">
                  <td class="px-6 py-4 font-medium">{{teacher.user.firstName}} {{teacher.user.lastName}}</td>
                  <td class="px-6 py-4">{{teacher.employeeId}}</td>
                  <td class="px-6 py-4">{{teacher.qualification || 'N/A'}}</td>
                  <td class="px-6 py-4">
                    @for (s of teacher.subjects; track s.id) {
                      <span class="inline-block px-2 py-1 bg-blue-100 text-blue-700 rounded text-xs mr-1">{{s.name}}</span>
                    }
                  </td>
                  <td class="px-6 py-4">
                    @for (c of teacher.classes; track c.id) {
                      <span class="inline-block px-2 py-1 bg-green-100 text-green-700 rounded text-xs mr-1">{{c.name}}</span>
                    }
                  </td>
                  <td class="px-6 py-4">
                    <button (click)="deleteTeacher(teacher.id)" class="text-red-600 hover:text-red-800">Delete</button>
                  </td>
                </tr>
              }
            </tbody>
          </table>
        </div>
      }

      @if (showAdd) {
        <div class="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
          <div class="bg-white rounded-xl p-6 w-full max-w-lg">
            <h2 class="text-xl font-bold mb-4">Add Teacher</h2>
            <form (ngSubmit)="addTeacher()">
              <div class="grid grid-cols-2 gap-4">
                <div><label class="block text-sm font-medium mb-1">Username</label><input [(ngModel)]="newTeacher.username" name="username" class="w-full px-3 py-2 border rounded-lg" required></div>
                <div><label class="block text-sm font-medium mb-1">Password</label><input [(ngModel)]="newTeacher.password" name="password" type="password" class="w-full px-3 py-2 border rounded-lg" required></div>
                <div><label class="block text-sm font-medium mb-1">First Name</label><input [(ngModel)]="newTeacher.firstName" name="firstName" class="w-full px-3 py-2 border rounded-lg" required></div>
                <div><label class="block text-sm font-medium mb-1">Last Name</label><input [(ngModel)]="newTeacher.lastName" name="lastName" class="w-full px-3 py-2 border rounded-lg" required></div>
                <div><label class="block text-sm font-medium mb-1">Employee ID</label><input [(ngModel)]="newTeacher.employeeId" name="empId" class="w-full px-3 py-2 border rounded-lg" required></div>
                <div><label class="block text-sm font-medium mb-1">Qualification</label><input [(ngModel)]="newTeacher.qualification" name="qual" class="w-full px-3 py-2 border rounded-lg"></div>
                <div><label class="block text-sm font-medium mb-1">Email</label><input [(ngModel)]="newTeacher.email" name="email" type="email" class="w-full px-3 py-2 border rounded-lg"></div>
                <div><label class="block text-sm font-medium mb-1">Phone</label><input [(ngModel)]="newTeacher.phone" name="phone" class="w-full px-3 py-2 border rounded-lg"></div>
              </div>
              <div class="flex justify-end gap-3 mt-6">
                <button type="button" (click)="showAdd = false" class="px-4 py-2 border rounded-lg">Cancel</button>
                <button type="submit" class="px-4 py-2 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700">Save</button>
              </div>
            </form>
          </div>
        </div>
      }
    </div>
  `
})
export class TeachersComponent implements OnInit {
  teachers: any[] = [];
  loading = true;
  search = '';
  showAdd = false;
  newTeacher: any = {};

  constructor(private api: ApiService) {}

  ngOnInit() { this.load(); }

  load() { this.api.getTeachers().subscribe({ next: (res) => { this.teachers = res; this.loading = false; }, error: () => this.loading = false }); }

  get filteredTeachers() {
    if (!this.search) return this.teachers;
    const s = this.search.toLowerCase();
    return this.teachers.filter(t => `${t.user.firstName} ${t.user.lastName} ${t.employeeId}`.toLowerCase().includes(s));
  }

  addTeacher() {
    this.api.createTeacher(this.newTeacher).subscribe({ next: () => { this.showAdd = false; this.newTeacher = {}; this.load(); } });
  }

  deleteTeacher(id: number) {
    if (confirm('Delete this teacher?')) { this.api.deleteTeacher(id).subscribe({ next: () => this.load() }); }
  }
}
