// frontend/src/pages/Reports.tsx
import { useEffect, useState } from 'react';
import api from '../utils/api';
import { BarChart3, Users, BookOpen } from 'lucide-react';

interface ReportData {
  totalStudents: number;
  totalTeachers: number;
  totalClasses: number;
  totalSubjects: number;
  classDistribution: { name: string; section?: string; students: number }[];
}

export default function Reports() {
  const [reportData, setReportData] = useState<ReportData | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    api.get('/reports/overview').then(res => { setReportData(res.data); setLoading(false); }).catch(() => setLoading(false));
  }, []);

  if (loading) return <div className="flex items-center justify-center h-64"><div className="animate-spin rounded-full h-8 w-8 border-b-2 border-indigo-600"></div></div>;

  return (
    <div>
      <div className="mb-6">
        <h1 className="text-2xl font-bold text-gray-900">Reports & Analytics</h1>
        <p className="text-gray-500 mt-1">Overview and insights</p>
      </div>

      {reportData && (
        <>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 mb-8">
            <div className="bg-white rounded-xl shadow-sm border p-6 flex items-center gap-4">
              <div className="bg-blue-500 p-3 rounded-lg"><Users size={24} className="text-white" /></div>
              <div><p className="text-sm text-gray-500">Students</p><p className="text-2xl font-bold">{reportData.totalStudents}</p></div>
            </div>
            <div className="bg-white rounded-xl shadow-sm border p-6 flex items-center gap-4">
              <div className="bg-green-500 p-3 rounded-lg"><Users size={24} className="text-white" /></div>
              <div><p className="text-sm text-gray-500">Teachers</p><p className="text-2xl font-bold">{reportData.totalTeachers}</p></div>
            </div>
            <div className="bg-white rounded-xl shadow-sm border p-6 flex items-center gap-4">
              <div className="bg-purple-500 p-3 rounded-lg"><BookOpen size={24} className="text-white" /></div>
              <div><p className="text-sm text-gray-500">Classes</p><p className="text-2xl font-bold">{reportData.totalClasses}</p></div>
            </div>
            <div className="bg-white rounded-xl shadow-sm border p-6 flex items-center gap-4">
              <div className="bg-amber-500 p-3 rounded-lg"><BarChart3 size={24} className="text-white" /></div>
              <div><p className="text-sm text-gray-500">Subjects</p><p className="text-2xl font-bold">{reportData.totalSubjects}</p></div>
            </div>
          </div>

          <div className="bg-white rounded-xl shadow-sm border p-6">
            <h2 className="text-lg font-semibold text-gray-900 mb-4">Class Distribution</h2>
            <div className="space-y-3">
              {reportData.classDistribution.map((cls, i) => {
                const maxStudents = Math.max(...reportData.classDistribution.map(c => c.students), 1);
                const percentage = (cls.students / maxStudents) * 100;
                return (
                  <div key={i}>
                    <div className="flex items-center justify-between mb-1">
                      <span className="text-sm font-medium text-gray-700">{cls.name} {cls.section || ''}</span>
                      <span className="text-sm text-gray-500">{cls.students} students</span>
                    </div>
                    <div className="w-full bg-gray-100 rounded-full h-3">
                      <div className="bg-indigo-600 h-3 rounded-full transition-all" style={{ width: `${percentage}%` }} />
                    </div>
                  </div>
                );
              })}
            </div>
          </div>
        </>
      )}
    </div>
  );
}

// frontend/src/app/pages/reports/reports.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ApiService } from '../../services/api.service';

@Component({
  selector: 'app-reports',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div class="p-6">
      <h1 class="text-2xl font-bold text-gray-800 mb-6">Reports</h1>

      @if (loading) {
        <div class="flex justify-center py-12"><div class="animate-spin rounded-full h-12 w-12 border-b-2 border-indigo-600"></div></div>
      } @else {
        <!-- Stats Cards -->
        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-8">
          <div class="bg-white rounded-xl shadow p-6 border-l-4 border-blue-500">
            <p class="text-sm text-gray-500">Total Students</p>
            <p class="text-3xl font-bold text-gray-800">{{overview?.totalStudents || 0}}</p>
          </div>
          <div class="bg-white rounded-xl shadow p-6 border-l-4 border-green-500">
            <p class="text-sm text-gray-500">Total Teachers</p>
            <p class="text-3xl font-bold text-gray-800">{{overview?.totalTeachers || 0}}</p>
          </div>
          <div class="bg-white rounded-xl shadow p-6 border-l-4 border-purple-500">
            <p class="text-sm text-gray-500">Total Classes</p>
            <p class="text-3xl font-bold text-gray-800">{{overview?.totalClasses || 0}}</p>
          </div>
          <div class="bg-white rounded-xl shadow p-6 border-l-4 border-orange-500">
            <p class="text-sm text-gray-500">Total Subjects</p>
            <p class="text-3xl font-bold text-gray-800">{{overview?.totalSubjects || 0}}</p>
          </div>
        </div>

        <!-- Class Distribution -->
        @if (overview?.classDistribution) {
          <div class="bg-white rounded-xl shadow p-6 mb-8">
            <h3 class="text-lg font-semibold mb-4">Class Distribution</h3>
            <div class="space-y-4">
              @for (cls of overview.classDistribution; track cls.name) {
                <div>
                  <div class="flex justify-between text-sm mb-1">
                    <span class="font-medium">{{cls.name}} {{cls.section}}</span>
                    <span class="text-gray-500">{{cls.students}} students</span>
                  </div>
                  <div class="w-full bg-gray-200 rounded-full h-3">
                    <div class="bg-indigo-600 h-3 rounded-full transition-all" [style.width.%]="maxStudents > 0 ? (cls.students / maxStudents * 100) : 0"></div>
                  </div>
                </div>
              }
            </div>
          </div>
        }

        <!-- Financial Report -->
        @if (feesReport) {
          <div class="bg-white rounded-xl shadow p-6">
            <h3 class="text-lg font-semibold mb-4">Financial Summary</h3>
            <div class="grid grid-cols-1 md:grid-cols-3 gap-6">
              <div class="text-center p-4 bg-blue-50 rounded-lg">
                <p class="text-sm text-gray-500">Total Expected</p>
                <p class="text-xl font-bold text-blue-700">{{feesReport.totalExpected | number:'1.2-2'}} Birr</p>
              </div>
              <div class="text-center p-4 bg-green-50 rounded-lg">
                <p class="text-sm text-gray-500">Total Collected</p>
                <p class="text-xl font-bold text-green-700">{{feesReport.totalCollected | number:'1.2-2'}} Birr</p>
              </div>
              <div class="text-center p-4 bg-red-50 rounded-lg">
                <p class="text-sm text-gray-500">Outstanding</p>
                <p class="text-xl font-bold text-red-700">{{feesReport.outstanding | number:'1.2-2'}} Birr</p>
              </div>
            </div>
            @if (feesReport.collectionRate !== undefined) {
              <div class="mt-4">
                <div class="flex justify-between text-sm mb-1">
                  <span>Collection Rate</span>
                  <span class="font-medium">{{feesReport.collectionRate}}%</span>
                </div>
                <div class="w-full bg-gray-200 rounded-full h-3">
                  <div class="bg-green-500 h-3 rounded-full" [style.width.%]="feesReport.collectionRate"></div>
                </div>
              </div>
            }
          </div>
        }
      }
    </div>
  `
})
export class ReportsComponent implements OnInit {
  overview: any = null;
  feesReport: any = null;
  loading = true;
  maxStudents = 0;

  constructor(private api: ApiService) {}

  ngOnInit() {
    this.api.getOverviewReport().subscribe({
      next: (res) => {
        this.overview = res;
        if (res.classDistribution) {
          this.maxStudents = Math.max(...res.classDistribution.map((c: any) => c.students), 1);
        }
        this.loading = false;
      },
      error: () => this.loading = false
    });
    this.api.getFeesReport().subscribe({ next: (res) => this.feesReport = res });
  }
}
