// frontend/src/app/features/attendance/attendance.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ApiService } from '../../core/services/api.service';
import { Attendance, SchoolClass, Student } from '../../core/models/models';

@Component({
  selector: 'app-attendance',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
    <div>
      <div class="flex items-center justify-between mb-6">
        <h1 class="text-2xl font-bold text-gray-800">Attendance</h1>
        <button (click)="showBulkForm = !showBulkForm" class="bg-primary-600 text-white px-4 py-2 rounded-lg hover:bg-primary-700">
          <i class="pi pi-plus mr-2"></i>{{ showBulkForm ? 'Cancel' : 'Take Attendance' }}
        </button>
      </div>

      <!-- Filters -->
      <div class="bg-white rounded-xl shadow-sm border border-gray-100 p-4 mb-6">
        <div class="flex gap-4">
          <select [(ngModel)]="filterClassId" (ngModelChange)="loadAttendance()" class="px-4 py-2 border border-gray-300 rounded-lg">
            <option [ngValue]="undefined">All Classes</option>
            @for (c of classes; track c.id) { <option [ngValue]="c.id">{{ c.name }} {{ c.section }}</option> }
          </select>
          <input type="date" [(ngModel)]="filterDate" (ngModelChange)="loadAttendance()" class="px-4 py-2 border border-gray-300 rounded-lg">
        </div>
      </div>

      <!-- Bulk Attendance Form -->
      @if (showBulkForm) {
        <div class="bg-white rounded-xl shadow-sm border border-gray-100 p-6 mb-6">
          <h3 class="text-lg font-semibold mb-4">Record Attendance</h3>
          <div class="flex gap-4 mb-4">
            <select [(ngModel)]="bulkClassId" (ngModelChange)="loadClassStudents()" class="px-4 py-2 border border-gray-300 rounded-lg">
              <option [ngValue]="undefined">Select Class</option>
              @for (c of classes; track c.id) { <option [ngValue]="c.id">{{ c.name }} {{ c.section }}</option> }
            </select>
            <input type="date" [(ngModel)]="bulkDate" class="px-4 py-2 border border-gray-300 rounded-lg">
          </div>

          @if (classStudents.length > 0) {
            <table class="w-full text-sm mb-4">
              <thead class="bg-gray-50">
                <tr>
                  <th class="text-left py-2 px-4">Student</th>
                  <th class="text-left py-2 px-4">Status</th>
                  <th class="text-left py-2 px-4">Remarks</th>
                </tr>
              </thead>
              <tbody>
                @for (entry of bulkEntries; track entry.studentId; let i = $index) {
                  <tr class="border-t border-gray-100">
                    <td class="py-2 px-4">{{ entry.studentName }}</td>
                    <td class="py-2 px-4">
                      <select [(ngModel)]="entry.status" [name]="'status_' + i" class="px-3 py-1 border border-gray-300 rounded-lg text-sm">
                        <option value="Present">Present</option>
                        <option value="Absent">Absent</option>
                        <option value="Late">Late</option>
                        <option value="Excused">Excused</option>
                      </select>
                    </td>
                    <td class="py-2 px-4">
                      <input type="text" [(ngModel)]="entry.remarks" [name]="'remarks_' + i" class="px-3 py-1 border border-gray-300 rounded-lg text-sm w-full">
                    </td>
                  </tr>
                }
              </tbody>
            </table>
            <button (click)="submitBulkAttendance()" class="bg-primary-600 text-white px-6 py-2 rounded-lg hover:bg-primary-700">
              Save Attendance
            </button>
          }
        </div>
      }

      <!-- Attendance Records -->
      <div class="bg-white rounded-xl shadow-sm border border-gray-100 overflow-hidden">
        <table class="w-full text-sm">
          <thead class="bg-gray-50">
            <tr>
              <th class="text-left py-3 px-4 font-medium text-gray-600">Date</th>
              <th class="text-left py-3 px-4 font-medium text-gray-600">Student</th>
              <th class="text-left py-3 px-4 font-medium text-gray-600">Status</th>
              <th class="text-left py-3 px-4 font-medium text-gray-600">Remarks</th>
            </tr>
          </thead>
          <tbody>
            @for (a of attendanceRecords; track a.id) {
              <tr class="border-t border-gray-100 hover:bg-gray-50">
                <td class="py-3 px-4">{{ a.date | date:'mediumDate' }}</td>
                <td class="py-3 px-4 font-medium">{{ a.studentName }}</td>
                <td class="py-3 px-4">
                  <span [class]="getStatusClass(a.status)">{{ a.status }}</span>
                </td>
                <td class="py-3 px-4 text-gray-600">{{ a.remarks }}</td>
              </tr>
            } @empty {
              <tr><td colspan="4" class="py-8 text-center text-gray-500">No attendance records found</td></tr>
            }
          </tbody>
        </table>
      </div>
    </div>
  `
})
export class AttendanceComponent implements OnInit {
  attendanceRecords: Attendance[] = [];
  classes: SchoolClass[] = [];
  classStudents: Student[] = [];
  filterClassId?: number;
  filterDate = '';
  showBulkForm = false;
  bulkClassId?: number;
  bulkDate = new Date().toISOString().split('T')[0];
  bulkEntries: any[] = [];

  constructor(private apiService: ApiService) {}

  ngOnInit(): void {
    this.loadAttendance();
    this.apiService.getClasses().subscribe(c => this.classes = c);
  }

  loadAttendance(): void {
    this.apiService.getAttendance(this.filterClassId, this.filterDate || undefined).subscribe(a => this.attendanceRecords = a);
  }

  loadClassStudents(): void {
    if (this.bulkClassId) {
      this.apiService.getStudents(undefined, this.bulkClassId).subscribe(students => {
        this.classStudents = students;
        this.bulkEntries = students.map(s => ({
          studentId: s.id,
          studentName: s.firstName + ' ' + s.lastName,
          status: 'Present',
          remarks: ''
        }));
      });
    }
  }

  submitBulkAttendance(): void {
    const statusMap: Record<string, number> = { Present: 0, Absent: 1, Late: 2, Excused: 3 };
    const data = {
      classId: this.bulkClassId,
      date: this.bulkDate,
      entries: this.bulkEntries.map(e => ({
        studentId: e.studentId,
        status: statusMap[e.status] ?? 0,
        remarks: e.remarks
      }))
    };
    this.apiService.bulkCreateAttendance(data).subscribe(() => {
      this.loadAttendance();
      this.showBulkForm = false;
    });
  }

  getStatusClass(status: string): string {
    const map: Record<string, string> = {
      Present: 'bg-green-100 text-green-700 px-2 py-1 rounded-full text-xs',
      Absent: 'bg-red-100 text-red-700 px-2 py-1 rounded-full text-xs',
      Late: 'bg-yellow-100 text-yellow-700 px-2 py-1 rounded-full text-xs',
      Excused: 'bg-blue-100 text-blue-700 px-2 py-1 rounded-full text-xs'
    };
    return map[status] || 'px-2 py-1 rounded-full text-xs';
  }
}

// frontend/src/pages/Attendance.tsx
import { useEffect, useState } from 'react';
import api from '../utils/api';
import type { ClassData } from '../types';
import { Calendar, CheckCircle, XCircle, Clock, AlertCircle } from 'lucide-react';

interface AttendanceRecord {
  id: string;
  date: string;
  status: string;
  studentId: string;
  student?: { user: { firstName: string; lastName: string } };
}

export default function Attendance() {
  const [classes, setClasses] = useState<ClassData[]>([]);
  const [selectedClass, setSelectedClass] = useState('');
  const [selectedDate, setSelectedDate] = useState(new Date().toISOString().split('T')[0]);
  const [records, setRecords] = useState<AttendanceRecord[]>([]);
  const [students, setStudents] = useState<{ id: string; user: { firstName: string; lastName: string } }[]>([]);
  const [attendanceData, setAttendanceData] = useState<Record<string, string>>({});
  const [loading, setLoading] = useState(false);
  const [saving, setSaving] = useState(false);

  useEffect(() => { api.get('/classes').then(res => setClasses(res.data)); }, []);

  useEffect(() => {
    if (selectedClass) {
      setLoading(true);
      Promise.all([
        api.get(`/classes/${selectedClass}`),
        api.get(`/attendance/class/${selectedClass}?date=${selectedDate}`),
      ]).then(([classRes, attRes]) => {
        setStudents(classRes.data.students || []);
        setRecords(attRes.data);
        const data: Record<string, string> = {};
        attRes.data.forEach((r: AttendanceRecord) => { data[r.studentId] = r.status; });
        classRes.data.students?.forEach((s: { id: string }) => {
          if (!data[s.id]) data[s.id] = 'PRESENT';
        });
        setAttendanceData(data);
        setLoading(false);
      }).catch(() => setLoading(false));
    }
  }, [selectedClass, selectedDate]);

  const saveAttendance = async () => {
    setSaving(true);
    try {
      const attendanceRecords = Object.entries(attendanceData).map(([studentId, status]) => ({ studentId, status }));
      await api.post('/attendance/bulk', { classId: selectedClass, date: selectedDate, records: attendanceRecords });
      alert('Attendance saved successfully!');
    } catch (error) { console.error('Error:', error); alert('Failed to save attendance'); }
    finally { setSaving(false); }
  };

  const statusIcons: Record<string, React.ReactNode> = {
    PRESENT: <CheckCircle size={16} className="text-green-500" />,
    ABSENT: <XCircle size={16} className="text-red-500" />,
    LATE: <Clock size={16} className="text-amber-500" />,
    EXCUSED: <AlertCircle size={16} className="text-blue-500" />,
  };

  const statusColors: Record<string, string> = {
    PRESENT: 'bg-green-100 text-green-700 border-green-300',
    ABSENT: 'bg-red-100 text-red-700 border-red-300',
    LATE: 'bg-amber-100 text-amber-700 border-amber-300',
    EXCUSED: 'bg-blue-100 text-blue-700 border-blue-300',
  };

  return (
    <div>
      <div className="mb-6">
        <h1 className="text-2xl font-bold text-gray-900">Attendance Management</h1>
        <p className="text-gray-500 mt-1">Record and view daily attendance</p>
      </div>

      <div className="bg-white rounded-xl shadow-sm border p-6 mb-6">
        <div className="flex flex-wrap gap-4">
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">Class</label>
            <select value={selectedClass} onChange={(e) => setSelectedClass(e.target.value)}
              className="px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-indigo-500 outline-none">
              <option value="">Select Class</option>
              {classes.map(c => <option key={c.id} value={c.id}>{c.name} {c.section || ''}</option>)}
            </select>
          </div>
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">Date</label>
            <div className="flex items-center gap-2">
              <Calendar size={18} className="text-gray-400" />
              <input type="date" value={selectedDate} onChange={(e) => setSelectedDate(e.target.value)}
                className="px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-indigo-500 outline-none" />
            </div>
          </div>
        </div>
      </div>

      {selectedClass && !loading && students.length > 0 && (
        <div className="bg-white rounded-xl shadow-sm border">
          <div className="p-4 border-b flex items-center justify-between">
            <p className="text-sm text-gray-600">{students.length} students</p>
            <button onClick={saveAttendance} disabled={saving}
              className="bg-indigo-600 text-white px-4 py-2 rounded-lg hover:bg-indigo-700 transition disabled:opacity-50">
              {saving ? 'Saving...' : 'Save Attendance'}
            </button>
          </div>
          <div className="divide-y">
            {students.map(student => (
              <div key={student.id} className="flex items-center justify-between px-6 py-3">
                <div className="flex items-center gap-3">
                  <div className="w-8 h-8 rounded-full bg-indigo-100 flex items-center justify-center text-sm font-medium text-indigo-600">
                    {student.user.firstName[0]}{student.user.lastName[0]}
                  </div>
                  <span className="font-medium text-gray-900">{student.user.firstName} {student.user.lastName}</span>
                </div>
                <div className="flex items-center gap-2">
                  {(['PRESENT', 'ABSENT', 'LATE', 'EXCUSED'] as const).map(status => (
                    <button key={status} onClick={() => setAttendanceData({ ...attendanceData, [student.id]: status })}
                      className={`flex items-center gap-1 px-3 py-1.5 rounded-full text-xs font-medium border transition ${
                        attendanceData[student.id] === status ? statusColors[status] : 'bg-gray-50 text-gray-400 border-gray-200'
                      }`}>
                      {statusIcons[status]} {status}
                    </button>
                  ))}
                </div>
              </div>
            ))}
          </div>
          {records.length > 0 && (
            <div className="p-4 bg-gray-50 border-t">
              <p className="text-xs text-gray-500">Attendance already recorded for this date. Saving will update existing records.</p>
            </div>
          )}
        </div>
      )}

      {loading && <div className="flex items-center justify-center h-32"><div className="animate-spin rounded-full h-8 w-8 border-b-2 border-indigo-600"></div></div>}
    </div>
  );
}
