// frontend/src/app/features/library/library.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ApiService } from '../../core/services/api.service';
import { LibraryBook, BookIssue, Student } from '../../core/models/models';

@Component({
  selector: 'app-library',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
    <div>
      <div class="flex items-center justify-between mb-6">
        <h1 class="text-2xl font-bold text-gray-800">Library</h1>
      </div>

      <div class="flex gap-2 mb-6">
        <button (click)="activeTab = 'books'" [class]="activeTab === 'books' ? 'bg-primary-600 text-white px-4 py-2 rounded-lg' : 'bg-white text-gray-700 px-4 py-2 rounded-lg border'">Books</button>
        <button (click)="activeTab = 'issues'" [class]="activeTab === 'issues' ? 'bg-primary-600 text-white px-4 py-2 rounded-lg' : 'bg-white text-gray-700 px-4 py-2 rounded-lg border'">Issued Books</button>
        <button (click)="activeTab = 'issue'" [class]="activeTab === 'issue' ? 'bg-primary-600 text-white px-4 py-2 rounded-lg' : 'bg-white text-gray-700 px-4 py-2 rounded-lg border'">Issue Book</button>
      </div>

      @if (activeTab === 'books') {
        <div class="flex gap-4 mb-4">
          <input type="text" [(ngModel)]="searchTerm" (ngModelChange)="loadBooks()" placeholder="Search books..."
            class="flex-1 px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary-500 outline-none">
          <button (click)="showBookForm = !showBookForm" class="bg-primary-600 text-white px-4 py-2 rounded-lg hover:bg-primary-700">
            <i class="pi pi-plus mr-2"></i>Add Book
          </button>
        </div>

        @if (showBookForm) {
          <div class="bg-white rounded-xl shadow-sm border border-gray-100 p-6 mb-6">
            <form (ngSubmit)="saveBook()">
              <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                <div>
                  <label class="block text-sm font-medium text-gray-700 mb-1">Title</label>
                  <input type="text" [(ngModel)]="bookForm.title" name="title" class="w-full px-3 py-2 border border-gray-300 rounded-lg" required>
                </div>
                <div>
                  <label class="block text-sm font-medium text-gray-700 mb-1">Author</label>
                  <input type="text" [(ngModel)]="bookForm.author" name="author" class="w-full px-3 py-2 border border-gray-300 rounded-lg" required>
                </div>
                <div>
                  <label class="block text-sm font-medium text-gray-700 mb-1">ISBN</label>
                  <input type="text" [(ngModel)]="bookForm.isbn" name="isbn" class="w-full px-3 py-2 border border-gray-300 rounded-lg">
                </div>
                <div>
                  <label class="block text-sm font-medium text-gray-700 mb-1">Category</label>
                  <input type="text" [(ngModel)]="bookForm.category" name="category" class="w-full px-3 py-2 border border-gray-300 rounded-lg">
                </div>
                <div>
                  <label class="block text-sm font-medium text-gray-700 mb-1">Total Copies</label>
                  <input type="number" [(ngModel)]="bookForm.totalCopies" name="totalCopies" class="w-full px-3 py-2 border border-gray-300 rounded-lg" required>
                </div>
              </div>
              <div class="mt-4">
                <button type="submit" class="bg-primary-600 text-white px-6 py-2 rounded-lg hover:bg-primary-700">Save</button>
              </div>
            </form>
          </div>
        }

        <div class="bg-white rounded-xl shadow-sm border border-gray-100 overflow-hidden">
          <table class="w-full text-sm">
            <thead class="bg-gray-50">
              <tr>
                <th class="text-left py-3 px-4 font-medium text-gray-600">Title</th>
                <th class="text-left py-3 px-4 font-medium text-gray-600">Author</th>
                <th class="text-left py-3 px-4 font-medium text-gray-600">ISBN</th>
                <th class="text-left py-3 px-4 font-medium text-gray-600">Category</th>
                <th class="text-left py-3 px-4 font-medium text-gray-600">Available</th>
                <th class="text-left py-3 px-4 font-medium text-gray-600">Actions</th>
              </tr>
            </thead>
            <tbody>
              @for (b of books; track b.id) {
                <tr class="border-t border-gray-100 hover:bg-gray-50">
                  <td class="py-3 px-4 font-medium">{{ b.title }}</td>
                  <td class="py-3 px-4">{{ b.author }}</td>
                  <td class="py-3 px-4 font-mono text-xs">{{ b.isbn }}</td>
                  <td class="py-3 px-4">{{ b.category }}</td>
                  <td class="py-3 px-4">
                    <span [class]="b.availableCopies > 0 ? 'text-green-600 font-medium' : 'text-red-600 font-medium'">
                      {{ b.availableCopies }}/{{ b.totalCopies }}
                    </span>
                  </td>
                  <td class="py-3 px-4">
                    <button (click)="deleteBook(b.id)" class="text-red-600 hover:text-red-800"><i class="pi pi-trash"></i></button>
                  </td>
                </tr>
              } @empty {
                <tr><td colspan="6" class="py-8 text-center text-gray-500">No books found</td></tr>
              }
            </tbody>
          </table>
        </div>
      }

      @if (activeTab === 'issues') {
        <div class="bg-white rounded-xl shadow-sm border border-gray-100 overflow-hidden">
          <table class="w-full text-sm">
            <thead class="bg-gray-50">
              <tr>
                <th class="text-left py-3 px-4 font-medium text-gray-600">Book</th>
                <th class="text-left py-3 px-4 font-medium text-gray-600">Student</th>
                <th class="text-left py-3 px-4 font-medium text-gray-600">Issue Date</th>
                <th class="text-left py-3 px-4 font-medium text-gray-600">Due Date</th>
                <th class="text-left py-3 px-4 font-medium text-gray-600">Return Date</th>
                <th class="text-left py-3 px-4 font-medium text-gray-600">Fine</th>
                <th class="text-left py-3 px-4 font-medium text-gray-600">Actions</th>
              </tr>
            </thead>
            <tbody>
              @for (i of issues; track i.id) {
                <tr class="border-t border-gray-100 hover:bg-gray-50">
                  <td class="py-3 px-4 font-medium">{{ i.bookTitle }}</td>
                  <td class="py-3 px-4">{{ i.studentName }}</td>
                  <td class="py-3 px-4">{{ i.issueDate | date:'mediumDate' }}</td>
                  <td class="py-3 px-4">{{ i.dueDate | date:'mediumDate' }}</td>
                  <td class="py-3 px-4">{{ i.returnDate ? (i.returnDate | date:'mediumDate') : 'Not returned' }}</td>
                  <td class="py-3 px-4">\${{ i.fine.toFixed(2) }}</td>
                  <td class="py-3 px-4">
                    @if (!i.returnDate) {
                      <button (click)="returnBook(i.id)" class="bg-green-100 text-green-700 px-3 py-1 rounded-lg text-xs hover:bg-green-200">Return</button>
                    }
                  </td>
                </tr>
              } @empty {
                <tr><td colspan="7" class="py-8 text-center text-gray-500">No issued books</td></tr>
              }
            </tbody>
          </table>
        </div>
      }

      @if (activeTab === 'issue') {
        <div class="bg-white rounded-xl shadow-sm border border-gray-100 p-6">
          <h3 class="text-lg font-semibold mb-4">Issue a Book</h3>
          <form (ngSubmit)="issueBook()">
            <div class="grid grid-cols-1 md:grid-cols-3 gap-4">
              <div>
                <label class="block text-sm font-medium text-gray-700 mb-1">Book</label>
                <select [(ngModel)]="issueForm.bookId" name="bookId" class="w-full px-3 py-2 border border-gray-300 rounded-lg" required>
                  @for (b of books; track b.id) {
                    <option [ngValue]="b.id" [disabled]="b.availableCopies === 0">{{ b.title }} ({{ b.availableCopies }} available)</option>
                  }
                </select>
              </div>
              <div>
                <label class="block text-sm font-medium text-gray-700 mb-1">Student</label>
                <select [(ngModel)]="issueForm.studentId" name="studentId" class="w-full px-3 py-2 border border-gray-300 rounded-lg" required>
                  @for (s of students; track s.id) { <option [ngValue]="s.id">{{ s.firstName }} {{ s.lastName }}</option> }
                </select>
              </div>
              <div>
                <label class="block text-sm font-medium text-gray-700 mb-1">Due Date</label>
                <input type="date" [(ngModel)]="issueForm.dueDate" name="dueDate" class="w-full px-3 py-2 border border-gray-300 rounded-lg" required>
              </div>
            </div>
            <div class="mt-4">
              <button type="submit" class="bg-primary-600 text-white px-6 py-2 rounded-lg hover:bg-primary-700">Issue Book</button>
            </div>
          </form>
        </div>
      }
    </div>
  `
})
export class LibraryComponent implements OnInit {
  activeTab = 'books';
  books: LibraryBook[] = [];
  issues: BookIssue[] = [];
  students: Student[] = [];
  searchTerm = '';
  showBookForm = false;
  bookForm: any = {};
  issueForm: any = {};

  constructor(private apiService: ApiService) {}

  ngOnInit(): void {
    this.loadBooks();
    this.loadIssues();
    this.apiService.getStudents().subscribe(s => this.students = s);
  }

  loadBooks(): void { this.apiService.getBooks(this.searchTerm || undefined).subscribe(b => this.books = b); }
  loadIssues(): void { this.apiService.getBookIssues().subscribe(i => this.issues = i); }

  saveBook(): void {
    this.apiService.createBook(this.bookForm).subscribe(() => {
      this.loadBooks();
      this.showBookForm = false;
      this.bookForm = {};
    });
  }

  deleteBook(id: number): void {
    if (confirm('Are you sure?')) this.apiService.deleteBook(id).subscribe(() => this.loadBooks());
  }

  issueBook(): void {
    this.apiService.issueBook(this.issueForm).subscribe(() => {
      this.loadIssues();
      this.loadBooks();
      this.issueForm = {};
      this.activeTab = 'issues';
    });
  }

  returnBook(id: number): void {
    this.apiService.returnBook(id).subscribe(() => {
      this.loadIssues();
      this.loadBooks();
    });
  }
}

// frontend/src/pages/Library.tsx
import { useEffect, useState } from 'react';
import api from '../utils/api';
import type { Book, BookIssue } from '../types';
import { Search, Plus, BookOpen, RotateCcw } from 'lucide-react';

export default function LibraryPage() {
  const [books, setBooks] = useState<Book[]>([]);
  const [issues, setIssues] = useState<BookIssue[]>([]);
  const [loading, setLoading] = useState(true);
  const [activeTab, setActiveTab] = useState<'books' | 'issues'>('books');
  const [search, setSearch] = useState('');

  useEffect(() => {
    Promise.all([
      api.get('/library/books'),
      api.get('/library/issues'),
    ]).then(([booksRes, issuesRes]) => {
      setBooks(booksRes.data);
      setIssues(issuesRes.data);
      setLoading(false);
    }).catch(() => setLoading(false));
  }, []);

  const returnBook = async (issueId: string) => {
    try {
      await api.put(`/library/return/${issueId}`);
      const { data } = await api.get('/library/issues');
      setIssues(data);
      const booksData = await api.get('/library/books');
      setBooks(booksData.data);
    } catch (error) { console.error('Error:', error); }
  };

  const filteredBooks = books.filter(b => `${b.title} ${b.author}`.toLowerCase().includes(search.toLowerCase()));

  if (loading) return <div className="flex items-center justify-center h-64"><div className="animate-spin rounded-full h-8 w-8 border-b-2 border-indigo-600"></div></div>;

  return (
    <div>
      <div className="flex items-center justify-between mb-6">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">Library</h1>
          <p className="text-gray-500 mt-1">{books.length} books in collection</p>
        </div>
        <button className="flex items-center gap-2 bg-indigo-600 text-white px-4 py-2 rounded-lg hover:bg-indigo-700 transition">
          <Plus size={18} /> Add Book
        </button>
      </div>

      <div className="bg-white rounded-xl shadow-sm border">
        <div className="border-b flex">
          <button onClick={() => setActiveTab('books')}
            className={`px-6 py-3 text-sm font-medium transition ${activeTab === 'books' ? 'text-indigo-600 border-b-2 border-indigo-600' : 'text-gray-500'}`}>
            Books ({books.length})
          </button>
          <button onClick={() => setActiveTab('issues')}
            className={`px-6 py-3 text-sm font-medium transition ${activeTab === 'issues' ? 'text-indigo-600 border-b-2 border-indigo-600' : 'text-gray-500'}`}>
            Issued ({issues.filter(i => !i.returnDate).length})
          </button>
        </div>

        {activeTab === 'books' && (
          <>
            <div className="p-4 border-b">
              <div className="relative">
                <Search size={18} className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" />
                <input type="text" placeholder="Search books..." value={search} onChange={(e) => setSearch(e.target.value)}
                  className="w-full pl-10 pr-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-indigo-500 outline-none" />
              </div>
            </div>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 p-4">
              {filteredBooks.map(book => (
                <div key={book.id} className="border rounded-xl p-4 hover:shadow-md transition">
                  <div className="flex items-start gap-3">
                    <div className="bg-indigo-100 p-2 rounded-lg"><BookOpen size={20} className="text-indigo-600" /></div>
                    <div className="flex-1">
                      <h3 className="font-medium text-gray-900">{book.title}</h3>
                      <p className="text-sm text-gray-500">{book.author}</p>
                      {book.isbn && <p className="text-xs text-gray-400 mt-1">ISBN: {book.isbn}</p>}
                      <div className="flex items-center justify-between mt-3">
                        <span className="text-xs text-gray-500">{book.category}</span>
                        <span className={`text-xs px-2 py-1 rounded-full ${book.available > 0 ? 'bg-green-100 text-green-700' : 'bg-red-100 text-red-700'}`}>
                          {book.available}/{book.quantity} available
                        </span>
                      </div>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </>
        )}

        {activeTab === 'issues' && (
          <div className="overflow-x-auto">
            <table className="w-full">
              <thead className="bg-gray-50">
                <tr>
                  <th className="text-left px-6 py-3 text-xs font-medium text-gray-500 uppercase">Book</th>
                  <th className="text-left px-6 py-3 text-xs font-medium text-gray-500 uppercase">Student</th>
                  <th className="text-left px-6 py-3 text-xs font-medium text-gray-500 uppercase">Issue Date</th>
                  <th className="text-left px-6 py-3 text-xs font-medium text-gray-500 uppercase">Due Date</th>
                  <th className="text-left px-6 py-3 text-xs font-medium text-gray-500 uppercase">Status</th>
                  <th className="text-left px-6 py-3 text-xs font-medium text-gray-500 uppercase">Actions</th>
                </tr>
              </thead>
              <tbody className="divide-y">
                {issues.map(issue => (
                  <tr key={issue.id} className="hover:bg-gray-50">
                    <td className="px-6 py-4 font-medium text-gray-900">{issue.book?.title}</td>
                    <td className="px-6 py-4 text-sm text-gray-600">{issue.student?.user?.firstName} {issue.student?.user?.lastName}</td>
                    <td className="px-6 py-4 text-sm text-gray-600">{new Date(issue.issueDate).toLocaleDateString()}</td>
                    <td className="px-6 py-4 text-sm text-gray-600">{new Date(issue.dueDate).toLocaleDateString()}</td>
                    <td className="px-6 py-4">
                      <span className={`text-xs px-2 py-1 rounded-full ${issue.returnDate ? 'bg-green-100 text-green-700' : 'bg-amber-100 text-amber-700'}`}>
                        {issue.returnDate ? 'Returned' : 'Issued'}
                      </span>
                    </td>
                    <td className="px-6 py-4">
                      {!issue.returnDate && (
                        <button onClick={() => returnBook(issue.id)} className="flex items-center gap-1 text-sm text-indigo-600 hover:text-indigo-800">
                          <RotateCcw size={14} /> Return
                        </button>
                      )}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  );
}
