// frontend/src/app/features/students/students.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ApiService } from '../../core/services/api.service';
import { AuthService } from '../../core/services/auth.service';
import { Student, SchoolClass } from '../../core/models/models';

@Component({
  selector: 'app-students',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
    <div>
      <div class="flex items-center justify-between mb-6">
        <h1 class="text-2xl font-bold text-gray-800">Students</h1>
        @if (authService.hasRole(['Admin'])) {
          <button (click)="showForm = !showForm" class="bg-primary-600 text-white px-4 py-2 rounded-lg hover:bg-primary-700 transition-colors">
            <i class="pi pi-plus mr-2"></i>{{ showForm ? 'Cancel' : 'Add Student' }}
          </button>
        }
      </div>

      <!-- Search -->
      <div class="bg-white rounded-xl shadow-sm border border-gray-100 p-4 mb-6">
        <div class="flex gap-4">
          <input type="text" [(ngModel)]="searchTerm" (ngModelChange)="loadStudents()" placeholder="Search students..."
            class="flex-1 px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary-500 outline-none">
          <select [(ngModel)]="selectedClassId" (ngModelChange)="loadStudents()" class="px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-primary-500 outline-none">
            <option [ngValue]="undefined">All Classes</option>
            @for (c of classes; track c.id) {
              <option [ngValue]="c.id">{{ c.name }} {{ c.section }}</option>
            }
          </select>
        </div>
      </div>

      <!-- Add/Edit Form -->
      @if (showForm) {
        <div class="bg-white rounded-xl shadow-sm border border-gray-100 p-6 mb-6">
          <h3 class="text-lg font-semibold mb-4">{{ editingStudent ? 'Edit Student' : 'Add New Student' }}</h3>
          <form (ngSubmit)="saveStudent()">
            <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
              <div>
                <label class="block text-sm font-medium text-gray-700 mb-1">Student ID</label>
                <input type="text" [(ngModel)]="form.studentIdNumber" name="studentIdNumber" class="w-full px-3 py-2 border border-gray-300 rounded-lg" required [disabled]="!!editingStudent">
              </div>
              <div>
                <label class="block text-sm font-medium text-gray-700 mb-1">First Name</label>
                <input type="text" [(ngModel)]="form.firstName" name="firstName" class="w-full px-3 py-2 border border-gray-300 rounded-lg" required>
              </div>
              <div>
                <label class="block text-sm font-medium text-gray-700 mb-1">Last Name</label>
                <input type="text" [(ngModel)]="form.lastName" name="lastName" class="w-full px-3 py-2 border border-gray-300 rounded-lg" required>
              </div>
              <div>
                <label class="block text-sm font-medium text-gray-700 mb-1">Date of Birth</label>
                <input type="date" [(ngModel)]="form.dateOfBirth" name="dateOfBirth" class="w-full px-3 py-2 border border-gray-300 rounded-lg">
              </div>
              <div>
                <label class="block text-sm font-medium text-gray-700 mb-1">Gender</label>
                <select [(ngModel)]="form.gender" name="gender" class="w-full px-3 py-2 border border-gray-300 rounded-lg">
                  <option value="Male">Male</option>
                  <option value="Female">Female</option>
                </select>
              </div>
              <div>
                <label class="block text-sm font-medium text-gray-700 mb-1">Email</label>
                <input type="email" [(ngModel)]="form.email" name="email" class="w-full px-3 py-2 border border-gray-300 rounded-lg">
              </div>
              <div>
                <label class="block text-sm font-medium text-gray-700 mb-1">Phone</label>
                <input type="text" [(ngModel)]="form.phoneNumber" name="phoneNumber" class="w-full px-3 py-2 border border-gray-300 rounded-lg">
              </div>
              <div>
                <label class="block text-sm font-medium text-gray-700 mb-1">Address</label>
                <input type="text" [(ngModel)]="form.address" name="address" class="w-full px-3 py-2 border border-gray-300 rounded-lg">
              </div>
              <div>
                <label class="block text-sm font-medium text-gray-700 mb-1">Class</label>
                <select [(ngModel)]="form.classId" name="classId" class="w-full px-3 py-2 border border-gray-300 rounded-lg">
                  <option [ngValue]="null">No Class</option>
                  @for (c of classes; track c.id) {
                    <option [ngValue]="c.id">{{ c.name }} {{ c.section }}</option>
                  }
                </select>
              </div>
            </div>
            <div class="mt-4 flex gap-2">
              <button type="submit" class="bg-primary-600 text-white px-6 py-2 rounded-lg hover:bg-primary-700">Save</button>
              <button type="button" (click)="cancelEdit()" class="bg-gray-200 text-gray-700 px-6 py-2 rounded-lg hover:bg-gray-300">Cancel</button>
            </div>
          </form>
        </div>
      }

      <!-- Students Table -->
      <div class="bg-white rounded-xl shadow-sm border border-gray-100 overflow-hidden">
        <table class="w-full text-sm">
          <thead class="bg-gray-50">
            <tr>
              <th class="text-left py-3 px-4 font-medium text-gray-600">ID</th>
              <th class="text-left py-3 px-4 font-medium text-gray-600">Name</th>
              <th class="text-left py-3 px-4 font-medium text-gray-600">Email</th>
              <th class="text-left py-3 px-4 font-medium text-gray-600">Class</th>
              <th class="text-left py-3 px-4 font-medium text-gray-600">Gender</th>
              <th class="text-left py-3 px-4 font-medium text-gray-600">Status</th>
              @if (authService.hasRole(['Admin'])) {
                <th class="text-left py-3 px-4 font-medium text-gray-600">Actions</th>
              }
            </tr>
          </thead>
          <tbody>
            @for (student of students; track student.id) {
              <tr class="border-t border-gray-100 hover:bg-gray-50">
                <td class="py-3 px-4 font-mono text-xs">{{ student.studentIdNumber }}</td>
                <td class="py-3 px-4 font-medium">{{ student.firstName }} {{ student.lastName }}</td>
                <td class="py-3 px-4 text-gray-600">{{ student.email }}</td>
                <td class="py-3 px-4">{{ student.className || 'Unassigned' }}</td>
                <td class="py-3 px-4">{{ student.gender }}</td>
                <td class="py-3 px-4">
                  <span [class]="student.isActive ? 'bg-green-100 text-green-700 px-2 py-1 rounded-full text-xs' : 'bg-red-100 text-red-700 px-2 py-1 rounded-full text-xs'">
                    {{ student.isActive ? 'Active' : 'Inactive' }}
                  </span>
                </td>
                @if (authService.hasRole(['Admin'])) {
                  <td class="py-3 px-4">
                    <button (click)="editStudent(student)" class="text-primary-600 hover:text-primary-800 mr-2"><i class="pi pi-pencil"></i></button>
                    <button (click)="deleteStudent(student.id)" class="text-red-600 hover:text-red-800"><i class="pi pi-trash"></i></button>
                  </td>
                }
              </tr>
            } @empty {
              <tr><td colspan="7" class="py-8 text-center text-gray-500">No students found</td></tr>
            }
          </tbody>
        </table>
      </div>
    </div>
  `
})
export class StudentsComponent implements OnInit {
  students: Student[] = [];
  classes: SchoolClass[] = [];
  searchTerm = '';
  selectedClassId?: number;
  showForm = false;
  editingStudent: Student | null = null;
  form: any = {};

  constructor(private apiService: ApiService, public authService: AuthService) {}

  ngOnInit(): void {
    this.loadStudents();
    this.apiService.getClasses().subscribe(c => this.classes = c);
  }

  loadStudents(): void {
    this.apiService.getStudents(this.searchTerm || undefined, this.selectedClassId).subscribe(s => this.students = s);
  }

  editStudent(student: Student): void {
    this.editingStudent = student;
    this.form = { ...student };
    this.showForm = true;
  }

  cancelEdit(): void {
    this.editingStudent = null;
    this.form = {};
    this.showForm = false;
  }

  saveStudent(): void {
    if (this.editingStudent) {
      this.apiService.updateStudent(this.editingStudent.id, this.form).subscribe(() => {
        this.loadStudents();
        this.cancelEdit();
      });
    } else {
      this.apiService.createStudent(this.form).subscribe(() => {
        this.loadStudents();
        this.cancelEdit();
      });
    }
  }

  deleteStudent(id: number): void {
    if (confirm('Are you sure you want to delete this student?')) {
      this.apiService.deleteStudent(id).subscribe(() => this.loadStudents());
    }
  }
}

// frontend/src/pages/Students.tsx
import { useEffect, useState } from 'react';
import api from '../utils/api';
import type { Student } from '../types';
import { Search, Plus, Eye, Edit, Trash2, X } from 'lucide-react';

export default function Students() {
  const [students, setStudents] = useState<Student[]>([]);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState('');
  const [selectedStudent, setSelectedStudent] = useState<Student | null>(null);
  const [showModal, setShowModal] = useState(false);

  useEffect(() => {
    fetchStudents();
  }, []);

  const fetchStudents = async () => {
    try {
      const { data } = await api.get('/students');
      setStudents(data);
    } catch (error) {
      console.error('Error fetching students:', error);
    } finally {
      setLoading(false);
    }
  };

  const deleteStudent = async (id: string) => {
    if (!confirm('Are you sure you want to delete this student?')) return;
    try {
      await api.delete(`/students/${id}`);
      setStudents(students.filter(s => s.id !== id));
    } catch (error) {
      console.error('Error deleting student:', error);
    }
  };

  const viewStudent = async (id: string) => {
    try {
      const { data } = await api.get(`/students/${id}`);
      setSelectedStudent(data);
      setShowModal(true);
    } catch (error) {
      console.error('Error fetching student:', error);
    }
  };

  const filtered = students.filter(s =>
    `${s.user.firstName} ${s.user.lastName} ${s.admissionNumber}`.toLowerCase().includes(search.toLowerCase())
  );

  if (loading) return <div className="flex items-center justify-center h-64"><div className="animate-spin rounded-full h-8 w-8 border-b-2 border-indigo-600"></div></div>;

  return (
    <div>
      <div className="flex items-center justify-between mb-6">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">Students</h1>
          <p className="text-gray-500 mt-1">{students.length} total students</p>
        </div>
        <button className="flex items-center gap-2 bg-indigo-600 text-white px-4 py-2 rounded-lg hover:bg-indigo-700 transition">
          <Plus size={18} /> Add Student
        </button>
      </div>

      <div className="bg-white rounded-xl shadow-sm border">
        <div className="p-4 border-b">
          <div className="relative">
            <Search size={18} className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" />
            <input
              type="text"
              placeholder="Search students..."
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              className="w-full pl-10 pr-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 outline-none"
            />
          </div>
        </div>
        <div className="overflow-x-auto">
          <table className="w-full">
            <thead className="bg-gray-50">
              <tr>
                <th className="text-left px-6 py-3 text-xs font-medium text-gray-500 uppercase">Student</th>
                <th className="text-left px-6 py-3 text-xs font-medium text-gray-500 uppercase">Admission #</th>
                <th className="text-left px-6 py-3 text-xs font-medium text-gray-500 uppercase">Class</th>
                <th className="text-left px-6 py-3 text-xs font-medium text-gray-500 uppercase">Gender</th>
                <th className="text-left px-6 py-3 text-xs font-medium text-gray-500 uppercase">Status</th>
                <th className="text-left px-6 py-3 text-xs font-medium text-gray-500 uppercase">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y">
              {filtered.map(student => (
                <tr key={student.id} className="hover:bg-gray-50">
                  <td className="px-6 py-4">
                    <div className="flex items-center gap-3">
                      <div className="w-8 h-8 rounded-full bg-indigo-100 flex items-center justify-center text-sm font-medium text-indigo-600">
                        {student.user.firstName[0]}{student.user.lastName[0]}
                      </div>
                      <div>
                        <p className="font-medium text-gray-900">{student.user.firstName} {student.user.lastName}</p>
                        <p className="text-sm text-gray-500">{student.user.email}</p>
                      </div>
                    </div>
                  </td>
                  <td className="px-6 py-4 text-sm text-gray-600">{student.admissionNumber}</td>
                  <td className="px-6 py-4 text-sm text-gray-600">{student.class?.name} {student.class?.section || ''}</td>
                  <td className="px-6 py-4 text-sm text-gray-600">{student.gender}</td>
                  <td className="px-6 py-4">
                    <span className={`inline-flex px-2 py-1 text-xs rounded-full ${student.user.isActive ? 'bg-green-100 text-green-700' : 'bg-red-100 text-red-700'}`}>
                      {student.user.isActive ? 'Active' : 'Inactive'}
                    </span>
                  </td>
                  <td className="px-6 py-4">
                    <div className="flex items-center gap-2">
                      <button onClick={() => viewStudent(student.id)} className="p-1 hover:bg-gray-100 rounded"><Eye size={16} className="text-gray-500" /></button>
                      <button className="p-1 hover:bg-gray-100 rounded"><Edit size={16} className="text-blue-500" /></button>
                      <button onClick={() => deleteStudent(student.id)} className="p-1 hover:bg-gray-100 rounded"><Trash2 size={16} className="text-red-500" /></button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {/* Student Detail Modal */}
      {showModal && selectedStudent && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
          <div className="bg-white rounded-xl max-w-2xl w-full max-h-[90vh] overflow-y-auto">
            <div className="flex items-center justify-between p-6 border-b">
              <h2 className="text-lg font-semibold">Student Details</h2>
              <button onClick={() => setShowModal(false)} className="p-1 hover:bg-gray-100 rounded"><X size={20} /></button>
            </div>
            <div className="p-6 space-y-4">
              <div className="grid grid-cols-2 gap-4">
                <div><p className="text-sm text-gray-500">Name</p><p className="font-medium">{selectedStudent.user.firstName} {selectedStudent.user.lastName}</p></div>
                <div><p className="text-sm text-gray-500">Admission #</p><p className="font-medium">{selectedStudent.admissionNumber}</p></div>
                <div><p className="text-sm text-gray-500">Class</p><p className="font-medium">{selectedStudent.class?.name} {selectedStudent.class?.section || ''}</p></div>
                <div><p className="text-sm text-gray-500">Gender</p><p className="font-medium">{selectedStudent.gender}</p></div>
                <div><p className="text-sm text-gray-500">Date of Birth</p><p className="font-medium">{new Date(selectedStudent.dateOfBirth).toLocaleDateString()}</p></div>
                <div><p className="text-sm text-gray-500">Email</p><p className="font-medium">{selectedStudent.user.email}</p></div>
              </div>
              {selectedStudent.grades && selectedStudent.grades.length > 0 && (
                <div>
                  <h3 className="font-semibold mb-2">Recent Grades</h3>
                  <div className="space-y-2">
                    {selectedStudent.grades.map(g => (
                      <div key={g.id} className="flex justify-between items-center py-2 px-3 bg-gray-50 rounded">
                        <span className="text-sm">{g.subject?.name} - {g.examType}</span>
                        <span className="font-medium text-sm">{g.score}/{g.maxScore} ({g.grade})</span>
                      </div>
                    ))}
                  </div>
                </div>
              )}
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
