// frontend/src/app/pages/students/students.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ApiService } from '../../services/api.service';

@Component({
  selector: 'app-students',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
    <div class="p-6">
      <div class="flex justify-between items-center mb-6">
        <h1 class="text-2xl font-bold text-gray-800">Students</h1>
        <div class="flex gap-3">
          <input type="text" [(ngModel)]="search" placeholder="Search students..." class="px-4 py-2 border rounded-lg focus:ring-2 focus:ring-indigo-500">
          <button (click)="showAdd = true" class="px-4 py-2 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700">Add Student</button>
        </div>
      </div>
      @if (loading) {
        <div class="flex justify-center py-12"><div class="animate-spin rounded-full h-12 w-12 border-b-2 border-indigo-600"></div></div>
      } @else {
        <div class="bg-white rounded-xl shadow overflow-hidden">
          <table class="w-full text-sm">
            <thead class="bg-gray-50">
              <tr>
                <th class="text-left px-6 py-3 font-medium text-gray-500">Name</th>
                <th class="text-left px-6 py-3 font-medium text-gray-500">Admission #</th>
                <th class="text-left px-6 py-3 font-medium text-gray-500">Class</th>
                <th class="text-left px-6 py-3 font-medium text-gray-500">Gender</th>
                <th class="text-left px-6 py-3 font-medium text-gray-500">Parent</th>
                <th class="text-left px-6 py-3 font-medium text-gray-500">Actions</th>
              </tr>
            </thead>
            <tbody>
              @for (student of filteredStudents; track student.id) {
                <tr class="border-t hover:bg-gray-50">
                  <td class="px-6 py-4 font-medium">{{student.user.firstName}} {{student.user.lastName}}</td>
                  <td class="px-6 py-4">{{student.admissionNumber}}</td>
                  <td class="px-6 py-4">{{student.class?.name || 'N/A'}} {{student.class?.section || ''}}</td>
                  <td class="px-6 py-4">{{student.gender}}</td>
                  <td class="px-6 py-4">{{student.parent ? student.parent.user.firstName + ' ' + student.parent.user.lastName : 'N/A'}}</td>
                  <td class="px-6 py-4">
                    <button (click)="deleteStudent(student.id)" class="text-red-600 hover:text-red-800">Delete</button>
                  </td>
                </tr>
              }
            </tbody>
          </table>
          @if (filteredStudents.length === 0) {
            <div class="text-center py-8 text-gray-500">No students found</div>
          }
        </div>
      }

      <!-- Add Student Modal -->
      @if (showAdd) {
        <div class="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
          <div class="bg-white rounded-xl p-6 w-full max-w-lg max-h-[90vh] overflow-y-auto">
            <h2 class="text-xl font-bold mb-4">Add Student</h2>
            <form (ngSubmit)="addStudent()">
              <div class="grid grid-cols-2 gap-4">
                <div><label class="block text-sm font-medium mb-1">Username</label><input [(ngModel)]="newStudent.username" name="username" class="w-full px-3 py-2 border rounded-lg" required></div>
                <div><label class="block text-sm font-medium mb-1">Password</label><input [(ngModel)]="newStudent.password" name="password" type="password" class="w-full px-3 py-2 border rounded-lg" required></div>
                <div><label class="block text-sm font-medium mb-1">First Name</label><input [(ngModel)]="newStudent.firstName" name="firstName" class="w-full px-3 py-2 border rounded-lg" required></div>
                <div><label class="block text-sm font-medium mb-1">Last Name</label><input [(ngModel)]="newStudent.lastName" name="lastName" class="w-full px-3 py-2 border rounded-lg" required></div>
                <div><label class="block text-sm font-medium mb-1">Admission #</label><input [(ngModel)]="newStudent.admissionNumber" name="admNo" class="w-full px-3 py-2 border rounded-lg" required></div>
                <div><label class="block text-sm font-medium mb-1">Date of Birth</label><input [(ngModel)]="newStudent.dateOfBirth" name="dob" type="date" class="w-full px-3 py-2 border rounded-lg" required></div>
                <div><label class="block text-sm font-medium mb-1">Gender</label>
                  <select [(ngModel)]="newStudent.gender" name="gender" class="w-full px-3 py-2 border rounded-lg">
                    <option value="MALE">Male</option><option value="FEMALE">Female</option>
                  </select>
                </div>
                <div><label class="block text-sm font-medium mb-1">Email</label><input [(ngModel)]="newStudent.email" name="email" type="email" class="w-full px-3 py-2 border rounded-lg"></div>
              </div>
              <div class="flex justify-end gap-3 mt-6">
                <button type="button" (click)="showAdd = false" class="px-4 py-2 border rounded-lg">Cancel</button>
                <button type="submit" class="px-4 py-2 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700">Save</button>
              </div>
            </form>
          </div>
        </div>
      }
    </div>
  `
})
export class StudentsComponent implements OnInit {
  students: any[] = [];
  loading = true;
  search = '';
  showAdd = false;
  newStudent: any = { gender: 'MALE' };

  constructor(private api: ApiService) {}

  ngOnInit() { this.load(); }

  load() {
    this.api.getStudents().subscribe({ next: (res) => { this.students = res; this.loading = false; }, error: () => this.loading = false });
  }

  get filteredStudents() {
    if (!this.search) return this.students;
    const s = this.search.toLowerCase();
    return this.students.filter(st => `${st.user.firstName} ${st.user.lastName} ${st.admissionNumber}`.toLowerCase().includes(s));
  }

  addStudent() {
    this.api.createStudent(this.newStudent).subscribe({ next: () => { this.showAdd = false; this.newStudent = { gender: 'MALE' }; this.load(); } });
  }

  deleteStudent(id: number) {
    if (confirm('Delete this student?')) {
      this.api.deleteStudent(id).subscribe({ next: () => this.load() });
    }
  }
}

// frontend/src/pages/Students.tsx
import { useEffect, useState } from 'react';
import api from '../utils/api';
import type { Student } from '../types';
import { Search, Plus, Eye, Edit, Trash2, X } from 'lucide-react';

export default function Students() {
  const [students, setStudents] = useState<Student[]>([]);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState('');
  const [selectedStudent, setSelectedStudent] = useState<Student | null>(null);
  const [showModal, setShowModal] = useState(false);

  useEffect(() => {
    fetchStudents();
  }, []);

  const fetchStudents = async () => {
    try {
      const { data } = await api.get('/students');
      setStudents(data);
    } catch (error) {
      console.error('Error fetching students:', error);
    } finally {
      setLoading(false);
    }
  };

  const deleteStudent = async (id: string) => {
    if (!confirm('Are you sure you want to delete this student?')) return;
    try {
      await api.delete(`/students/${id}`);
      setStudents(students.filter(s => s.id !== id));
    } catch (error) {
      console.error('Error deleting student:', error);
    }
  };

  const viewStudent = async (id: string) => {
    try {
      const { data } = await api.get(`/students/${id}`);
      setSelectedStudent(data);
      setShowModal(true);
    } catch (error) {
      console.error('Error fetching student:', error);
    }
  };

  const filtered = students.filter(s =>
    `${s.user.firstName} ${s.user.lastName} ${s.admissionNumber}`.toLowerCase().includes(search.toLowerCase())
  );

  if (loading) return <div className="flex items-center justify-center h-64"><div className="animate-spin rounded-full h-8 w-8 border-b-2 border-indigo-600"></div></div>;

  return (
    <div>
      <div className="flex items-center justify-between mb-6">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">Students</h1>
          <p className="text-gray-500 mt-1">{students.length} total students</p>
        </div>
        <button className="flex items-center gap-2 bg-indigo-600 text-white px-4 py-2 rounded-lg hover:bg-indigo-700 transition">
          <Plus size={18} /> Add Student
        </button>
      </div>

      <div className="bg-white rounded-xl shadow-sm border">
        <div className="p-4 border-b">
          <div className="relative">
            <Search size={18} className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" />
            <input
              type="text"
              placeholder="Search students..."
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              className="w-full pl-10 pr-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 outline-none"
            />
          </div>
        </div>
        <div className="overflow-x-auto">
          <table className="w-full">
            <thead className="bg-gray-50">
              <tr>
                <th className="text-left px-6 py-3 text-xs font-medium text-gray-500 uppercase">Student</th>
                <th className="text-left px-6 py-3 text-xs font-medium text-gray-500 uppercase">Admission #</th>
                <th className="text-left px-6 py-3 text-xs font-medium text-gray-500 uppercase">Class</th>
                <th className="text-left px-6 py-3 text-xs font-medium text-gray-500 uppercase">Gender</th>
                <th className="text-left px-6 py-3 text-xs font-medium text-gray-500 uppercase">Status</th>
                <th className="text-left px-6 py-3 text-xs font-medium text-gray-500 uppercase">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y">
              {filtered.map(student => (
                <tr key={student.id} className="hover:bg-gray-50">
                  <td className="px-6 py-4">
                    <div className="flex items-center gap-3">
                      <div className="w-8 h-8 rounded-full bg-indigo-100 flex items-center justify-center text-sm font-medium text-indigo-600">
                        {student.user.firstName[0]}{student.user.lastName[0]}
                      </div>
                      <div>
                        <p className="font-medium text-gray-900">{student.user.firstName} {student.user.lastName}</p>
                        <p className="text-sm text-gray-500">{student.user.email}</p>
                      </div>
                    </div>
                  </td>
                  <td className="px-6 py-4 text-sm text-gray-600">{student.admissionNumber}</td>
                  <td className="px-6 py-4 text-sm text-gray-600">{student.class?.name} {student.class?.section || ''}</td>
                  <td className="px-6 py-4 text-sm text-gray-600">{student.gender}</td>
                  <td className="px-6 py-4">
                    <span className={`inline-flex px-2 py-1 text-xs rounded-full ${student.user.isActive ? 'bg-green-100 text-green-700' : 'bg-red-100 text-red-700'}`}>
                      {student.user.isActive ? 'Active' : 'Inactive'}
                    </span>
                  </td>
                  <td className="px-6 py-4">
                    <div className="flex items-center gap-2">
                      <button onClick={() => viewStudent(student.id)} className="p-1 hover:bg-gray-100 rounded"><Eye size={16} className="text-gray-500" /></button>
                      <button className="p-1 hover:bg-gray-100 rounded"><Edit size={16} className="text-blue-500" /></button>
                      <button onClick={() => deleteStudent(student.id)} className="p-1 hover:bg-gray-100 rounded"><Trash2 size={16} className="text-red-500" /></button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {/* Student Detail Modal */}
      {showModal && selectedStudent && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
          <div className="bg-white rounded-xl max-w-2xl w-full max-h-[90vh] overflow-y-auto">
            <div className="flex items-center justify-between p-6 border-b">
              <h2 className="text-lg font-semibold">Student Details</h2>
              <button onClick={() => setShowModal(false)} className="p-1 hover:bg-gray-100 rounded"><X size={20} /></button>
            </div>
            <div className="p-6 space-y-4">
              <div className="grid grid-cols-2 gap-4">
                <div><p className="text-sm text-gray-500">Name</p><p className="font-medium">{selectedStudent.user.firstName} {selectedStudent.user.lastName}</p></div>
                <div><p className="text-sm text-gray-500">Admission #</p><p className="font-medium">{selectedStudent.admissionNumber}</p></div>
                <div><p className="text-sm text-gray-500">Class</p><p className="font-medium">{selectedStudent.class?.name} {selectedStudent.class?.section || ''}</p></div>
                <div><p className="text-sm text-gray-500">Gender</p><p className="font-medium">{selectedStudent.gender}</p></div>
                <div><p className="text-sm text-gray-500">Date of Birth</p><p className="font-medium">{new Date(selectedStudent.dateOfBirth).toLocaleDateString()}</p></div>
                <div><p className="text-sm text-gray-500">Email</p><p className="font-medium">{selectedStudent.user.email}</p></div>
              </div>
              {selectedStudent.grades && selectedStudent.grades.length > 0 && (
                <div>
                  <h3 className="font-semibold mb-2">Recent Grades</h3>
                  <div className="space-y-2">
                    {selectedStudent.grades.map(g => (
                      <div key={g.id} className="flex justify-between items-center py-2 px-3 bg-gray-50 rounded">
                        <span className="text-sm">{g.subject?.name} - {g.examType}</span>
                        <span className="font-medium text-sm">{g.score}/{g.maxScore} ({g.grade})</span>
                      </div>
                    ))}
                  </div>
                </div>
              )}
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
