// frontend/src/app/features/subjects/subjects.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ApiService } from '../../core/services/api.service';
import { Subject, SchoolClass, Staff } from '../../core/models/models';

@Component({
  selector: 'app-subjects',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
    <div>
      <div class="flex items-center justify-between mb-6">
        <h1 class="text-2xl font-bold text-gray-800">Subjects</h1>
        <button (click)="showForm = !showForm" class="bg-primary-600 text-white px-4 py-2 rounded-lg hover:bg-primary-700">
          <i class="pi pi-plus mr-2"></i>{{ showForm ? 'Cancel' : 'Add Subject' }}
        </button>
      </div>

      @if (showForm) {
        <div class="bg-white rounded-xl shadow-sm border border-gray-100 p-6 mb-6">
          <h3 class="text-lg font-semibold mb-4">{{ editing ? 'Edit Subject' : 'Add New Subject' }}</h3>
          <form (ngSubmit)="save()">
            <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
              <div>
                <label class="block text-sm font-medium text-gray-700 mb-1">Subject Name</label>
                <input type="text" [(ngModel)]="form.name" name="name" class="w-full px-3 py-2 border border-gray-300 rounded-lg" required>
              </div>
              <div>
                <label class="block text-sm font-medium text-gray-700 mb-1">Code</label>
                <input type="text" [(ngModel)]="form.code" name="code" class="w-full px-3 py-2 border border-gray-300 rounded-lg" required>
              </div>
              <div>
                <label class="block text-sm font-medium text-gray-700 mb-1">Description</label>
                <input type="text" [(ngModel)]="form.description" name="description" class="w-full px-3 py-2 border border-gray-300 rounded-lg">
              </div>
              <div>
                <label class="block text-sm font-medium text-gray-700 mb-1">Class</label>
                <select [(ngModel)]="form.classId" name="classId" class="w-full px-3 py-2 border border-gray-300 rounded-lg">
                  <option [ngValue]="null">None</option>
                  @for (c of classes; track c.id) { <option [ngValue]="c.id">{{ c.name }} {{ c.section }}</option> }
                </select>
              </div>
              <div>
                <label class="block text-sm font-medium text-gray-700 mb-1">Teacher</label>
                <select [(ngModel)]="form.teacherId" name="teacherId" class="w-full px-3 py-2 border border-gray-300 rounded-lg">
                  <option [ngValue]="null">None</option>
                  @for (t of teachers; track t.id) { <option [ngValue]="t.id">{{ t.firstName }} {{ t.lastName }}</option> }
                </select>
              </div>
            </div>
            <div class="mt-4 flex gap-2">
              <button type="submit" class="bg-primary-600 text-white px-6 py-2 rounded-lg hover:bg-primary-700">Save</button>
              <button type="button" (click)="cancel()" class="bg-gray-200 text-gray-700 px-6 py-2 rounded-lg hover:bg-gray-300">Cancel</button>
            </div>
          </form>
        </div>
      }

      <div class="bg-white rounded-xl shadow-sm border border-gray-100 overflow-hidden">
        <table class="w-full text-sm">
          <thead class="bg-gray-50">
            <tr>
              <th class="text-left py-3 px-4 font-medium text-gray-600">Code</th>
              <th class="text-left py-3 px-4 font-medium text-gray-600">Name</th>
              <th class="text-left py-3 px-4 font-medium text-gray-600">Description</th>
              <th class="text-left py-3 px-4 font-medium text-gray-600">Class</th>
              <th class="text-left py-3 px-4 font-medium text-gray-600">Teacher</th>
              <th class="text-left py-3 px-4 font-medium text-gray-600">Actions</th>
            </tr>
          </thead>
          <tbody>
            @for (s of subjects; track s.id) {
              <tr class="border-t border-gray-100 hover:bg-gray-50">
                <td class="py-3 px-4 font-mono text-xs font-medium">{{ s.code }}</td>
                <td class="py-3 px-4 font-medium">{{ s.name }}</td>
                <td class="py-3 px-4 text-gray-600">{{ s.description }}</td>
                <td class="py-3 px-4">{{ s.className || '-' }}</td>
                <td class="py-3 px-4">{{ s.teacherName || '-' }}</td>
                <td class="py-3 px-4">
                  <button (click)="edit(s)" class="text-primary-600 hover:text-primary-800 mr-2"><i class="pi pi-pencil"></i></button>
                  <button (click)="deleteSubject(s.id)" class="text-red-600 hover:text-red-800"><i class="pi pi-trash"></i></button>
                </td>
              </tr>
            } @empty {
              <tr><td colspan="6" class="py-8 text-center text-gray-500">No subjects found</td></tr>
            }
          </tbody>
        </table>
      </div>
    </div>
  `
})
export class SubjectsComponent implements OnInit {
  subjects: Subject[] = [];
  classes: SchoolClass[] = [];
  teachers: Staff[] = [];
  showForm = false;
  editing: Subject | null = null;
  form: any = {};

  constructor(private apiService: ApiService) {}

  ngOnInit(): void {
    this.load();
    this.apiService.getClasses().subscribe(c => this.classes = c);
    this.apiService.getStaff().subscribe(s => this.teachers = s);
  }

  load(): void { this.apiService.getSubjects().subscribe(s => this.subjects = s); }
  edit(s: Subject): void { this.editing = s; this.form = { ...s }; this.showForm = true; }
  cancel(): void { this.editing = null; this.form = {}; this.showForm = false; }

  save(): void {
    if (this.editing) {
      this.apiService.updateSubject(this.editing.id, this.form).subscribe(() => { this.load(); this.cancel(); });
    } else {
      this.apiService.createSubject(this.form).subscribe(() => { this.load(); this.cancel(); });
    }
  }

  deleteSubject(id: number): void {
    if (confirm('Are you sure?')) this.apiService.deleteSubject(id).subscribe(() => this.load());
  }
}

// frontend/src/pages/Subjects.tsx
import { useEffect, useState } from 'react';
import api from '../utils/api';
import type { Subject } from '../types';
import { Search, Plus, Edit, Trash2 } from 'lucide-react';

export default function Subjects() {
  const [subjects, setSubjects] = useState<Subject[]>([]);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState('');

  useEffect(() => { fetchSubjects(); }, []);

  const fetchSubjects = async () => {
    try {
      const { data } = await api.get('/subjects');
      setSubjects(data);
    } catch (error) { console.error('Error:', error); }
    finally { setLoading(false); }
  };

  const deleteSubject = async (id: string) => {
    if (!confirm('Delete this subject?')) return;
    try {
      await api.delete(`/subjects/${id}`);
      setSubjects(subjects.filter(s => s.id !== id));
    } catch (error) { console.error('Error:', error); }
  };

  const filtered = subjects.filter(s => `${s.name} ${s.code}`.toLowerCase().includes(search.toLowerCase()));

  if (loading) return <div className="flex items-center justify-center h-64"><div className="animate-spin rounded-full h-8 w-8 border-b-2 border-indigo-600"></div></div>;

  return (
    <div>
      <div className="flex items-center justify-between mb-6">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">Subjects</h1>
          <p className="text-gray-500 mt-1">{subjects.length} total subjects</p>
        </div>
        <button className="flex items-center gap-2 bg-indigo-600 text-white px-4 py-2 rounded-lg hover:bg-indigo-700 transition">
          <Plus size={18} /> Add Subject
        </button>
      </div>

      <div className="bg-white rounded-xl shadow-sm border">
        <div className="p-4 border-b">
          <div className="relative">
            <Search size={18} className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" />
            <input type="text" placeholder="Search subjects..." value={search} onChange={(e) => setSearch(e.target.value)}
              className="w-full pl-10 pr-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 outline-none" />
          </div>
        </div>
        <div className="overflow-x-auto">
          <table className="w-full">
            <thead className="bg-gray-50">
              <tr>
                <th className="text-left px-6 py-3 text-xs font-medium text-gray-500 uppercase">Subject</th>
                <th className="text-left px-6 py-3 text-xs font-medium text-gray-500 uppercase">Code</th>
                <th className="text-left px-6 py-3 text-xs font-medium text-gray-500 uppercase">Teachers</th>
                <th className="text-left px-6 py-3 text-xs font-medium text-gray-500 uppercase">Classes</th>
                <th className="text-left px-6 py-3 text-xs font-medium text-gray-500 uppercase">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y">
              {filtered.map(subject => (
                <tr key={subject.id} className="hover:bg-gray-50">
                  <td className="px-6 py-4">
                    <p className="font-medium text-gray-900">{subject.name}</p>
                    <p className="text-sm text-gray-500">{subject.description || ''}</p>
                  </td>
                  <td className="px-6 py-4"><span className="inline-flex px-2 py-1 text-xs bg-gray-100 text-gray-700 rounded">{subject.code}</span></td>
                  <td className="px-6 py-4">
                    <div className="flex flex-wrap gap-1">
                      {subject.teachers?.map(t => (
                        <span key={t.teacher.id} className="text-xs text-gray-600">{t.teacher.user?.firstName} {t.teacher.user?.lastName}</span>
                      ))}
                    </div>
                  </td>
                  <td className="px-6 py-4 text-sm text-gray-600">{subject._count?.classes || 0}</td>
                  <td className="px-6 py-4">
                    <div className="flex items-center gap-2">
                      <button className="p-1 hover:bg-gray-100 rounded"><Edit size={16} className="text-blue-500" /></button>
                      <button onClick={() => deleteSubject(subject.id)} className="p-1 hover:bg-gray-100 rounded"><Trash2 size={16} className="text-red-500" /></button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
