// frontend/src/app/pages/subjects/subjects.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ApiService } from '../../services/api.service';

@Component({
  selector: 'app-subjects',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
    <div class="p-6">
      <div class="flex justify-between items-center mb-6">
        <h1 class="text-2xl font-bold text-gray-800">Subjects</h1>
        <button (click)="showAdd = true" class="px-4 py-2 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700">Add Subject</button>
      </div>
      @if (loading) {
        <div class="flex justify-center py-12"><div class="animate-spin rounded-full h-12 w-12 border-b-2 border-indigo-600"></div></div>
      } @else {
        <div class="bg-white rounded-xl shadow overflow-hidden">
          <table class="w-full text-sm">
            <thead class="bg-gray-50">
              <tr>
                <th class="text-left px-6 py-3 font-medium text-gray-500">Name</th>
                <th class="text-left px-6 py-3 font-medium text-gray-500">Code</th>
                <th class="text-left px-6 py-3 font-medium text-gray-500">Description</th>
                <th class="text-left px-6 py-3 font-medium text-gray-500">Teachers</th>
                <th class="text-left px-6 py-3 font-medium text-gray-500">Classes</th>
                <th class="text-left px-6 py-3 font-medium text-gray-500">Actions</th>
              </tr>
            </thead>
            <tbody>
              @for (subject of subjects; track subject.id) {
                <tr class="border-t hover:bg-gray-50">
                  <td class="px-6 py-4 font-medium">{{subject.name}}</td>
                  <td class="px-6 py-4"><span class="px-2 py-1 bg-gray-100 rounded text-xs">{{subject.code}}</span></td>
                  <td class="px-6 py-4 text-gray-600">{{subject.description || '-'}}</td>
                  <td class="px-6 py-4">
                    @for (t of subject.teachers; track t.teacher.id) {
                      <span class="inline-block px-2 py-1 bg-blue-100 text-blue-700 rounded text-xs mr-1">{{t.teacher.user.firstName}} {{t.teacher.user.lastName}}</span>
                    }
                  </td>
                  <td class="px-6 py-4">{{subject._count?.classes || 0}}</td>
                  <td class="px-6 py-4">
                    <button (click)="deleteSubject(subject.id)" class="text-red-600 hover:text-red-800">Delete</button>
                  </td>
                </tr>
              }
            </tbody>
          </table>
        </div>
      }

      @if (showAdd) {
        <div class="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
          <div class="bg-white rounded-xl p-6 w-full max-w-md">
            <h2 class="text-xl font-bold mb-4">Add Subject</h2>
            <form (ngSubmit)="addSubject()">
              <div class="space-y-4">
                <div><label class="block text-sm font-medium mb-1">Name</label><input [(ngModel)]="newSubject.name" name="name" class="w-full px-3 py-2 border rounded-lg" required></div>
                <div><label class="block text-sm font-medium mb-1">Code</label><input [(ngModel)]="newSubject.code" name="code" class="w-full px-3 py-2 border rounded-lg" required></div>
                <div><label class="block text-sm font-medium mb-1">Description</label><textarea [(ngModel)]="newSubject.description" name="desc" class="w-full px-3 py-2 border rounded-lg" rows="3"></textarea></div>
              </div>
              <div class="flex justify-end gap-3 mt-6">
                <button type="button" (click)="showAdd = false" class="px-4 py-2 border rounded-lg">Cancel</button>
                <button type="submit" class="px-4 py-2 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700">Save</button>
              </div>
            </form>
          </div>
        </div>
      }
    </div>
  `
})
export class SubjectsComponent implements OnInit {
  subjects: any[] = [];
  loading = true;
  showAdd = false;
  newSubject: any = {};

  constructor(private api: ApiService) {}
  ngOnInit() { this.load(); }
  load() { this.api.getSubjects().subscribe({ next: (res) => { this.subjects = res; this.loading = false; }, error: () => this.loading = false }); }
  addSubject() { this.api.createSubject(this.newSubject).subscribe({ next: () => { this.showAdd = false; this.newSubject = {}; this.load(); } }); }
  deleteSubject(id: number) { if (confirm('Delete?')) { this.api.deleteSubject(id).subscribe({ next: () => this.load() }); } }
}

// frontend/src/pages/Subjects.tsx
import { useEffect, useState } from 'react';
import api from '../utils/api';
import type { Subject } from '../types';
import { Search, Plus, Edit, Trash2 } from 'lucide-react';

export default function Subjects() {
  const [subjects, setSubjects] = useState<Subject[]>([]);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState('');

  useEffect(() => { fetchSubjects(); }, []);

  const fetchSubjects = async () => {
    try {
      const { data } = await api.get('/subjects');
      setSubjects(data);
    } catch (error) { console.error('Error:', error); }
    finally { setLoading(false); }
  };

  const deleteSubject = async (id: string) => {
    if (!confirm('Delete this subject?')) return;
    try {
      await api.delete(`/subjects/${id}`);
      setSubjects(subjects.filter(s => s.id !== id));
    } catch (error) { console.error('Error:', error); }
  };

  const filtered = subjects.filter(s => `${s.name} ${s.code}`.toLowerCase().includes(search.toLowerCase()));

  if (loading) return <div className="flex items-center justify-center h-64"><div className="animate-spin rounded-full h-8 w-8 border-b-2 border-indigo-600"></div></div>;

  return (
    <div>
      <div className="flex items-center justify-between mb-6">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">Subjects</h1>
          <p className="text-gray-500 mt-1">{subjects.length} total subjects</p>
        </div>
        <button className="flex items-center gap-2 bg-indigo-600 text-white px-4 py-2 rounded-lg hover:bg-indigo-700 transition">
          <Plus size={18} /> Add Subject
        </button>
      </div>

      <div className="bg-white rounded-xl shadow-sm border">
        <div className="p-4 border-b">
          <div className="relative">
            <Search size={18} className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" />
            <input type="text" placeholder="Search subjects..." value={search} onChange={(e) => setSearch(e.target.value)}
              className="w-full pl-10 pr-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 outline-none" />
          </div>
        </div>
        <div className="overflow-x-auto">
          <table className="w-full">
            <thead className="bg-gray-50">
              <tr>
                <th className="text-left px-6 py-3 text-xs font-medium text-gray-500 uppercase">Subject</th>
                <th className="text-left px-6 py-3 text-xs font-medium text-gray-500 uppercase">Code</th>
                <th className="text-left px-6 py-3 text-xs font-medium text-gray-500 uppercase">Teachers</th>
                <th className="text-left px-6 py-3 text-xs font-medium text-gray-500 uppercase">Classes</th>
                <th className="text-left px-6 py-3 text-xs font-medium text-gray-500 uppercase">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y">
              {filtered.map(subject => (
                <tr key={subject.id} className="hover:bg-gray-50">
                  <td className="px-6 py-4">
                    <p className="font-medium text-gray-900">{subject.name}</p>
                    <p className="text-sm text-gray-500">{subject.description || ''}</p>
                  </td>
                  <td className="px-6 py-4"><span className="inline-flex px-2 py-1 text-xs bg-gray-100 text-gray-700 rounded">{subject.code}</span></td>
                  <td className="px-6 py-4">
                    <div className="flex flex-wrap gap-1">
                      {subject.teachers?.map(t => (
                        <span key={t.teacher.id} className="text-xs text-gray-600">{t.teacher.user?.firstName} {t.teacher.user?.lastName}</span>
                      ))}
                    </div>
                  </td>
                  <td className="px-6 py-4 text-sm text-gray-600">{subject._count?.classes || 0}</td>
                  <td className="px-6 py-4">
                    <div className="flex items-center gap-2">
                      <button className="p-1 hover:bg-gray-100 rounded"><Edit size={16} className="text-blue-500" /></button>
                      <button onClick={() => deleteSubject(subject.id)} className="p-1 hover:bg-gray-100 rounded"><Trash2 size={16} className="text-red-500" /></button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
